(function(global){
  "use strict";
  const CONSENT_KEY="sc_library_sync_consent_v1",META_KEY="librarySync",BATCH_SIZE=100;
  let timer=null,context=null,lastUserId=null,authenticated=false;
  let status={phase:"unauthenticated",authenticated:false,consented:false,online:true,local:0,remote:0,pending:0,localPending:0,remotePending:0,conflicts:0,error:null};
  const listeners=new Set(),token=()=>global.appAuth&&global.appAuth.getAccessToken();
  const isOnline=()=>!global.navigator||global.navigator.onLine!==false;
  const hasConsent=()=>Boolean(global.storage&&global.storage.get(CONSENT_KEY,false));
  const clone=value=>global.structuredClone?global.structuredClone(value):JSON.parse(JSON.stringify(value));
  function emit(next={}){status=Object.freeze({...status,...next,authenticated,consented:hasConsent(),online:isOnline(),local:context?context.getSongs().length:0});listeners.forEach(listener=>{try{listener(status);}catch(_error){}});return status;}
  function request(path,options={}){const access=token();if(!access)return Promise.reject(new Error("Entre com sua conta para sincronizar."));return global.fetch(global.apiConfig.libraryEndpoint(path),{...options,headers:{"Content-Type":"application/json",Authorization:"Bearer "+access,...options.headers}}).then(async response=>{const body=response.status===204?null:await response.json().catch(()=>null);if(!response.ok){const error=new Error(body?.erro?.mensagem||"Não foi possível sincronizar a biblioteca.");error.code=body?.erro?.codigo||"sync_failed";error.status=response.status;throw error;}return body;});}
  function uuid(){return global.crypto?.randomUUID?.()||`song-${Date.now()}-${Math.random().toString(36).slice(2)}`;}
  function metadata(song){return song&&song[META_KEY]&&typeof song[META_KEY]==="object"?song[META_KEY]:{};}
  function wireSong(song){const copy=clone(song);delete copy[META_KEY];return copy;}
  function contentHash(song){let hash=2166136261;for(const char of JSON.stringify(wireSong(song))){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619);}return (hash>>>0).toString(16);}
  function prepared(songs){return songs.map(song=>metadata(song).clientId?song:{...song,[META_KEY]:{clientId:uuid(),serverVersion:null,syncedAt:null,contentHash:null,conflict:null}});}
  function sameSong(local,item){const meta=metadata(local);return Boolean(meta.clientId&&meta.clientId===item.clientId)||(!meta.clientId&&item.songData&&String(local.id)===String(item.songData.id));}
  function isDirty(song){const meta=metadata(song);return !meta.clientId||!meta.contentHash||meta.contentHash!==contentHash(song);}
  function conflictMeta(item){return {remoteVersion:item.version,remoteSongData:clone(item.songData),remoteUpdatedAt:item.updatedAt,detectedAt:new Date().toISOString()};}
  function inspect(songs,remote){let localPending=0,remotePending=0,conflicts=0;const matched=new Set();songs.forEach(song=>{const index=remote.findIndex(item=>sameSong(song,item)),meta=metadata(song),dirty=isDirty(song);if(meta.conflict){conflicts+=1;if(index>=0)matched.add(index);return;}if(index<0){localPending+=1;return;}matched.add(index);const item=remote[index],version=Number(meta.serverVersion)||0;if(item.version>version){if(dirty)conflicts+=1;else remotePending+=1;}else if(dirty)localPending+=1;});remote.forEach((_item,index)=>{if(!matched.has(index))remotePending+=1;});return {local:songs.length,remote:remote.length,localPending,remotePending,pending:localPending+remotePending,conflicts};}
  function merge(songs,remote){const values=songs.slice(),conflicts=[];let downloaded=0,applied=0;for(const item of remote){let index=values.findIndex(song=>sameSong(song,item));const sync={clientId:item.clientId,serverVersion:item.version,syncedAt:item.updatedAt,contentHash:contentHash(item.songData),conflict:null};if(index<0){values.push({...clone(item.songData),[META_KEY]:sync});downloaded+=1;continue;}const local=values[index],meta=metadata(local),version=Number(meta.serverVersion)||0,differs=JSON.stringify(wireSong(local))!==JSON.stringify(item.songData),dirty=isDirty(local);if(meta.conflict||differs&&dirty&&version<item.version){const conflict={clientId:item.clientId,title:local.title,localSongData:wireSong(local),remoteSongData:clone(item.songData),remoteVersion:item.version};values[index]={...local,[META_KEY]:{...meta,clientId:item.clientId,conflict:conflictMeta(item)}};conflicts.push(conflict);continue;}if(differs&&dirty)continue;if(differs||!meta.clientId){values[index]={...clone(item.songData),[META_KEY]:sync};applied+=1;}else values[index]={...local,[META_KEY]:sync};}return {songs:values,conflicts,downloaded,applied};}
  function phaseFor(metrics,options={}){if(!authenticated)return "unauthenticated";if(!isOnline())return "offline";if(metrics.conflicts)return "conflict";if(options.error)return "error";if(!hasConsent()&&metrics.localPending)return "needs-consent";if(metrics.pending)return "pending";return "synced";}
  function persist(values){context.setSongs(values);context.persist(values);context.render();}
  async function pull(options={}){if(!context||!token())return {downloaded:0,applied:0,conflicts:[]};if(!isOnline()){emit({phase:"offline",error:null});return {downloaded:0,applied:0,conflicts:[]};}if(!options.silent)emit({phase:"syncing",error:null});try{const body=await request(""),before=context.getSongs(),remote=body.songs||[],result=merge(before,remote);persist(result.songs);const metrics=inspect(result.songs,remote);emit({...metrics,phase:phaseFor(metrics),error:null});return {downloaded:result.downloaded,applied:result.applied,conflicts:result.conflicts,status};}catch(error){emit({phase:isOnline()?"error":"offline",error:error.message});throw error;}}
  async function review(){if(!authenticated||!token()){const current=emit({phase:"unauthenticated",remote:0,pending:0,localPending:0,remotePending:0,conflicts:0,error:null});return {...current,toUpload:0};}if(!isOnline()){const localPending=context.getSongs().filter(isDirty).length,current=emit({phase:"offline",localPending,pending:localPending+status.remotePending,error:null});return {...current,toUpload:current.localPending};}const result=await pull(),current=result.status;return {...current,toUpload:current.localPending};}
  async function syncNow(){if(!context||!token())throw new Error("Entre com sua conta para sincronizar.");if(!isOnline()){emit({phase:"offline",error:null});throw new Error("Você está offline. Suas músicas continuam disponíveis neste dispositivo.");}emit({phase:"syncing",error:null});try{const initial=(await request("")).songs||[],merged=merge(context.getSongs(),initial);persist(merged.songs);if(merged.conflicts.length){const metrics=inspect(merged.songs,initial);emit({...metrics,phase:"conflict",error:null});throw new Error(`${merged.conflicts.length} música(s) possuem alterações em dois dispositivos.`);}let songs=prepared(merged.songs);persist(songs);const pendingSongs=songs.filter(isDirty),items=pendingSongs.map(song=>({clientId:metadata(song).clientId,expectedVersion:metadata(song).serverVersion,songData:wireSong(song)})),results=[];for(let offset=0;offset<items.length;offset+=BATCH_SIZE){const body=await request("/sync",{method:"POST",body:JSON.stringify({items:items.slice(offset,offset+BATCH_SIZE)})});results.push(...body.results);}const byId=new Map(results.filter(item=>item.song).map(item=>[item.clientId,item.song]));songs=songs.map(song=>{const remote=byId.get(metadata(song).clientId);return remote?{...song,[META_KEY]:{clientId:remote.clientId,serverVersion:remote.version,syncedAt:remote.updatedAt,contentHash:contentHash(song),conflict:null}}:song;});persist(songs);global.storage.set(CONSENT_KEY,true);const finalRemote=(await request("")).songs||[],finalMerge=merge(songs,finalRemote);persist(finalMerge.songs);const metrics=inspect(finalMerge.songs,finalRemote),failed=results.filter(item=>item.outcome==="failed").length;emit({...metrics,phase:phaseFor(metrics,{error:failed>0}),error:failed?`${failed} música(s) ainda aguardam sincronização.`:null});return {total:results.length,attempted:items.length,created:results.filter(x=>x.outcome==="created").length,existing:results.filter(x=>x.outcome==="existing").length,updated:results.filter(x=>x.outcome==="updated").length,failed,status};}catch(error){if(status.phase!=="conflict")emit({phase:isOnline()?"error":"offline",error:error.message});throw error;}}
  function schedule(){const localPending=context?context.getSongs().filter(isDirty).length:0;if(!token()){emit({phase:"unauthenticated",localPending:0,pending:0,error:null});return;}if(!hasConsent()){emit({phase:isOnline()?"needs-consent":"offline",localPending,pending:localPending+status.remotePending,error:null});return;}emit({phase:isOnline()?"pending":"offline",localPending,pending:localPending+status.remotePending,error:null});if(!isOnline())return;clearTimeout(timer);timer=setTimeout(()=>syncNow().catch(()=>{}),1200);}
  function initialize(value){context=value;emit({local:context.getSongs().length});global.appAuth.subscribe(state=>{authenticated=Boolean(state.authenticated);const userId=authenticated&&state.user?.id;if(!userId){lastUserId=null;emit({phase:"unauthenticated",remote:0,pending:0,localPending:0,remotePending:0,conflicts:0,error:null});return;}if(userId===lastUserId){emit();return;}lastUserId=userId;pull().catch(()=>{});});global.addEventListener?.("online",()=>{emit({phase:"pending",error:null});if(hasConsent())schedule();else pull().catch(()=>{});});global.addEventListener?.("offline",()=>emit({phase:"offline",error:null}));}
  function subscribe(listener){listeners.add(listener);listener(status);return ()=>listeners.delete(listener);}
  function getStatus(){return status;}
  global.librarySync=Object.freeze({consentKey:CONSENT_KEY,initialize,pull,review,syncNow,schedule,merge,prepared,wireSong,contentHash,inspect,subscribe,getStatus});
})(window);
