(function(global){
  "use strict";
  const CONSENT_KEY="sc_library_sync_consent_v1",OWNER_CONSENT_KEY="sc_library_sync_consent_by_owner_v1",BACKUP_KEY="sc_library_migration_backup_v1",META_KEY="librarySync",BATCH_SIZE=100;
  let timer=null,context=null,lastUserId=null,authenticated=false,lastRemote=[],lastComparisons=[],lastRemoteContract=null,serverAudit=null,identityBlocked=false,migrationCandidate=false,migrationAuthorized=false;
  let status={phase:"unauthenticated",authenticated:false,consented:false,online:true,identityBlocked:false,migrationCandidate:false,backupReady:false,local:0,remote:0,pending:0,localPending:0,remotePending:0,conflicts:0,error:null};
  const listeners=new Set(),token=()=>global.appAuth&&global.appAuth.getAccessToken();
  const isOnline=()=>!global.navigator||global.navigator.onLine!==false;
  const ownerFlags=key=>{const value=global.storage&&global.storage.get(key,{});return value&&typeof value==="object"&&!Array.isArray(value)?value:{}};
  const hasConsent=()=>Boolean(lastUserId&&ownerFlags(OWNER_CONSENT_KEY)[lastUserId]);
  const hasBackup=()=>Boolean(lastUserId&&ownerFlags(BACKUP_KEY)[lastUserId]);
  function setOwnerFlag(key,value=true){if(!lastUserId||!global.storage)return false;const flags=ownerFlags(key);flags[lastUserId]=Boolean(value);return global.storage.set(key,flags);}
  const clone=value=>global.structuredClone?global.structuredClone(value):JSON.parse(JSON.stringify(value));
  function emit(next={}){status=Object.freeze({...status,...next,authenticated,consented:hasConsent(),online:isOnline(),identityBlocked,migrationCandidate,backupReady:hasBackup(),local:context?context.getSongs().length:0});listeners.forEach(listener=>{try{listener(status);}catch(_error){}});return status;}
  function request(path,options={}){const access=token();if(!access)return Promise.reject(new Error("Entre com sua conta para sincronizar."));return global.fetch(global.apiConfig.libraryEndpoint(path),{...options,headers:{"Content-Type":"application/json",Authorization:"Bearer "+access,...options.headers}}).then(async response=>{const body=response.status===204?null:await response.json().catch(()=>null);if(!response.ok){const error=new Error(body?.erro?.mensagem||"Não foi possível sincronizar a biblioteca.");error.code=body?.erro?.codigo||"sync_failed";error.status=response.status;throw error;}return body;});}
  function contractError(){const error=new Error("A resposta da biblioteca está em um formato incompatível. Nada foi enviado.");error.code="remote_contract_invalid";return error;}
  function normalizeRemoteRecord(item){if(!item||typeof item!=="object")return null;const clientId=String(item.clientId??item.client_id??"").trim(),songData=item.songData??item.song_data;if(!clientId||!songData||typeof songData!=="object"||Array.isArray(songData))return null;return {id:item.id??null,clientId,songData:clone(songData),version:Number(item.version)||0,updatedAt:item.updatedAt??item.updated_at??null,deletedAt:item.deletedAt??item.deleted_at??null};}
  function normalizeRemoteResponse(body){const source=Array.isArray(body)?"array":body?.songs!==undefined?"songs":body?.personalSongs!==undefined?"personalSongs":body?.personal_songs!==undefined?"personal_songs":body?.records!==undefined?"records":null,collection=source==="array"?body:source?body[source]:null;if(!Array.isArray(collection)){lastRemoteContract={valid:false,source,rawCount:null,normalizedCount:0,error:"missing_collection"};throw contractError();}const normalized=collection.map(normalizeRemoteRecord);if(normalized.some(item=>!item)){lastRemoteContract={valid:false,source,rawCount:collection.length,normalizedCount:normalized.filter(Boolean).length,error:"invalid_record"};throw contractError();}const active=normalized.filter(item=>!item.deletedAt);lastRemoteContract={valid:true,source,rawCount:collection.length,normalizedCount:active.length,recordShape:collection[0]?{clientId:collection[0].clientId!==undefined?"clientId":collection[0].client_id!==undefined?"client_id":"missing",songData:collection[0].songData!==undefined?"songData":collection[0].song_data!==undefined?"song_data":"missing"}:null};return active;}
  function normalizeSyncResults(body){if(!body||!Array.isArray(body.results))throw contractError();return body.results.map(item=>{const clientId=String(item?.clientId??item?.client_id??"").trim(),song=item?.song?normalizeRemoteRecord(item.song):null;if(!clientId)throw contractError();return {clientId,outcome:item.outcome,error:item.error,song};});}
  function requireConfirmedOwner(songs,remote){const established=(Array.isArray(songs)?songs:[]).filter(song=>{const meta=metadata(song);return meta.clientId&&(meta.serverVersion!=null||meta.syncedAt||meta.contentHash||meta.conflict);}).length;identityBlocked=remote.length===0&&established>0&&!(migrationCandidate&&migrationAuthorized&&hasBackup());lastRemote=clone(remote);if(identityBlocked){const error=new Error("A conta atual retornou uma biblioteca vazia diferente deste dispositivo. O envio foi bloqueado até confirmar a identidade.");error.code="library_owner_unconfirmed";throw error;}}
  function uuid(){return global.crypto?.randomUUID?.()||`song-${Date.now()}-${Math.random().toString(36).slice(2)}`;}
  function metadata(song){return song&&song[META_KEY]&&typeof song[META_KEY]==="object"?song[META_KEY]:{};}
  const VOLATILE_CONTENT_FIELDS=new Set(["createdAt","updatedAt"]),NORMALIZE_EPOCH="1970-01-01T00:00:00.000Z";
  function wireSong(song){const copy=clone(song);delete copy[META_KEY];return copy;}
  function canonical(value){if(Array.isArray(value))return value.map(canonical);if(value&&typeof value==="object"){const result={};Object.keys(value).sort().forEach(key=>{if(value[key]!==undefined)result[key]=canonical(value[key]);});return result;}return value;}
  function stableStringify(value){return JSON.stringify(canonical(value));}
  function withoutVolatileFields(value){if(Array.isArray(value))return value.map(withoutVolatileFields);if(value&&typeof value==="object"){const result={};Object.keys(value).forEach(key=>{if(!VOLATILE_CONTENT_FIELDS.has(key)&&value[key]!==undefined)result[key]=withoutVolatileFields(value[key]);});return result;}return value;}
  function musicalPayload(song){let value=wireSong(song);try{if(global.songModel?.create&&value?.title)value=global.songModel.create(value,{now:NORMALIZE_EPOCH,generateId:()=>"semantic-song"});}catch(_error){}return withoutVolatileFields(value);}
  function hashValue(value){let hash=2166136261;for(const char of stableStringify(value)){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619);}return (hash>>>0).toString(16);}
  function contentHash(song){return hashValue(musicalPayload(song));}
  function sameContent(left,right){return stableStringify(musicalPayload(left))===stableStringify(musicalPayload(right));}
  function valueSummary(value){if(value===undefined)return {type:"missing"};if(value===null)return {type:"null"};if(Array.isArray(value))return {type:"array",length:value.length,fingerprint:hashValue(canonical(value))};if(typeof value==="object")return {type:"object",keys:Object.keys(value).sort(),fingerprint:hashValue(canonical(value))};if(typeof value==="string")return {type:"string",length:value.length,fingerprint:hashValue(value)};return {type:typeof value,value};}
  function structuralDiff(left,right,limit=100){const differences=[];function visit(a,b,path){if(differences.length>=limit)return;if(stableStringify(a)===stableStringify(b))return;if(Array.isArray(a)&&Array.isArray(b)){const size=Math.max(a.length,b.length);for(let index=0;index<size;index+=1)visit(a[index],b[index],`${path}[${index}]`);return;}if(a&&b&&typeof a==="object"&&typeof b==="object"&&!Array.isArray(a)&&!Array.isArray(b)){const keys=new Set([...Object.keys(a),...Object.keys(b)]);[...keys].sort().forEach(key=>visit(a[key],b[key],path?`${path}.${key}`:key));return;}differences.push({path:path||"$",local:valueSummary(a),remote:valueSummary(b)});}visit(left,right,"");return {truncated:differences.length>=limit,differences};}
  function prepared(songs){return songs.map(song=>metadata(song).clientId?song:{...song,[META_KEY]:{clientId:uuid(),serverVersion:null,syncedAt:null,contentHash:null,conflict:null}});}
  function sameSong(local,item){const meta=metadata(local);return Boolean(meta.clientId&&meta.clientId===item.clientId)||(!meta.clientId&&item.songData&&String(local.id)===String(item.songData.id));}
  function isDirty(song){const meta=metadata(song);return !meta.clientId||!meta.contentHash||meta.contentHash!==contentHash(song);}
  function conflictMeta(item){return {remoteVersion:item.version,remoteSongData:clone(item.songData),remoteUpdatedAt:item.updatedAt,detectedAt:new Date().toISOString()};}
  function inspect(songs,remote){let localPending=0,remotePending=0,conflicts=0;const matched=new Set();songs.forEach(song=>{const index=remote.findIndex(item=>sameSong(song,item)),meta=metadata(song),dirty=isDirty(song);if(meta.conflict){conflicts+=1;if(index>=0)matched.add(index);return;}if(index<0){localPending+=1;return;}matched.add(index);const item=remote[index],version=Number(meta.serverVersion)||0;if(item.version>version){if(dirty)conflicts+=1;else remotePending+=1;}else if(dirty)localPending+=1;});remote.forEach((_item,index)=>{if(!matched.has(index))remotePending+=1;});return {local:songs.length,remote:remote.length,localPending,remotePending,pending:localPending+remotePending,conflicts};}
  function merge(songs,remote){lastRemote=clone(remote);lastComparisons=[];const values=songs.slice(),conflicts=[];let downloaded=0,applied=0;for(const item of remote){let index=values.findIndex(song=>sameSong(song,item));const sync={clientId:item.clientId,serverVersion:item.version,syncedAt:item.updatedAt,contentHash:contentHash(item.songData),conflict:null};if(index<0){values.push({...clone(item.songData),[META_KEY]:sync});downloaded+=1;continue;}const local=values[index],meta=metadata(local),version=Number(meta.serverVersion)||0,differs=!sameContent(local,item.songData),dirty=isDirty(local),decision=classification(local,item);lastComparisons.push({localId:local.id??null,remoteClientId:item.clientId,status:decision.status,reason:decision.reason,rawDiff:structuralDiff(wireSong(local),item.songData),semanticDiff:structuralDiff(musicalPayload(local),musicalPayload(item.songData))});if(differs&&(meta.conflict||dirty&&version<item.version)){const conflict={clientId:item.clientId,title:local.title,localSongData:wireSong(local),remoteSongData:clone(item.songData),remoteVersion:item.version};values[index]={...local,[META_KEY]:{...meta,clientId:item.clientId,conflict:conflictMeta(item)}};conflicts.push(conflict);continue;}if(differs&&dirty)continue;if(differs||!meta.clientId||meta.conflict){values[index]={...clone(item.songData),[META_KEY]:sync};applied+=1;}else values[index]={...local,[META_KEY]:sync};}return {songs:values,conflicts,downloaded,applied};}
  function phaseFor(metrics,options={}){if(!authenticated)return "unauthenticated";if(!isOnline())return "offline";if(metrics.conflicts)return "conflict";if(options.error)return "error";if(!hasConsent()&&metrics.localPending)return "needs-consent";if(metrics.pending)return "pending";return "synced";}
  function persist(values){context.setSongs(values);context.persist(values);context.render();}
  async function pull(options={}){if(!context||!token())return {downloaded:0,applied:0,conflicts:[]};if(!isOnline()){emit({phase:"offline",error:null});return {downloaded:0,applied:0,conflicts:[]};}if(!options.silent)emit({phase:"syncing",error:null});try{const body=await request(""),before=context.getSongs(),remote=normalizeRemoteResponse(body);requireConfirmedOwner(before,remote);const result=merge(before,remote);persist(result.songs);const metrics=inspect(result.songs,remote);if(remote.length&&!migrationCandidate&&!result.conflicts.length)setOwnerFlag(OWNER_CONSENT_KEY,true);emit({...metrics,phase:phaseFor(metrics),error:null});return {downloaded:result.downloaded,applied:result.applied,conflicts:result.conflicts,status};}catch(error){emit({phase:isOnline()?"error":"offline",remote:lastRemote.length,localPending:0,remotePending:0,pending:0,conflicts:0,error:error.message});throw error;}}
  async function review(){if(!authenticated||!token()){const current=emit({phase:"unauthenticated",remote:0,pending:0,localPending:0,remotePending:0,conflicts:0,error:null});return {...current,toUpload:0};}if(!isOnline()){const localPending=context.getSongs().filter(isDirty).length,current=emit({phase:"offline",localPending,pending:localPending+status.remotePending,error:null});return {...current,toUpload:current.localPending};}const result=await pull(),current=result.status;return {...current,toUpload:current.localPending};}
  async function syncNow(){if(!context||!token())throw new Error("Entre com sua conta para sincronizar.");if(migrationCandidate&&!hasBackup())throw new Error("Baixe o backup completo antes de salvar estas músicas na sua conta.");if(!isOnline()){emit({phase:"offline",error:null});throw new Error("Você está offline. Suas músicas continuam disponíveis neste dispositivo.");}migrationAuthorized=migrationCandidate;emit({phase:"syncing",error:null});try{const current=context.getSongs(),initial=normalizeRemoteResponse(await request(""));requireConfirmedOwner(current,initial);const merged=merge(current,initial);persist(merged.songs);if(merged.conflicts.length){const metrics=inspect(merged.songs,initial);emit({...metrics,phase:"conflict",error:null});throw new Error(`${merged.conflicts.length} música(s) possuem alterações em dois dispositivos.`);}let songs=prepared(merged.songs);persist(songs);const pendingSongs=songs.filter(isDirty),items=pendingSongs.map(song=>({clientId:metadata(song).clientId,expectedVersion:metadata(song).serverVersion,songData:wireSong(song)})),results=[];for(let offset=0;offset<items.length;offset+=BATCH_SIZE){const body=await request("/sync",{method:"POST",body:JSON.stringify({items:items.slice(offset,offset+BATCH_SIZE)})});results.push(...normalizeSyncResults(body));}const byId=new Map(results.filter(item=>item.song).map(item=>[item.clientId,item.song]));songs=songs.map(song=>{const remote=byId.get(metadata(song).clientId);return remote?{...song,[META_KEY]:{clientId:remote.clientId,serverVersion:remote.version,syncedAt:remote.updatedAt,contentHash:contentHash(song),conflict:null}}:song;});persist(songs);const finalRemote=normalizeRemoteResponse(await request(""));requireConfirmedOwner(songs,finalRemote);const finalMerge=merge(songs,finalRemote);persist(finalMerge.songs);const metrics=inspect(finalMerge.songs,finalRemote),failed=results.filter(item=>item.outcome==="failed").length;if(!failed&&!metrics.pending&&!metrics.conflicts){setOwnerFlag(OWNER_CONSENT_KEY,true);global.storage.set(CONSENT_KEY,true);if(migrationCandidate&&context.confirmOwner&&!context.confirmOwner(finalMerge.songs))throw new Error("A nuvem confirmou as músicas, mas o cache desta conta não pôde ser finalizado.");migrationCandidate=false;}emit({...metrics,phase:phaseFor(metrics,{error:failed>0}),error:failed?`${failed} música(s) ainda aguardam sincronização.`:null});return {total:results.length,attempted:items.length,created:results.filter(x=>x.outcome==="created").length,existing:results.filter(x=>x.outcome==="existing").length,updated:results.filter(x=>x.outcome==="updated").length,failed,status};}catch(error){if(status.phase!=="conflict")emit({phase:isOnline()?"error":"offline",remote:lastRemote.length,localPending:0,remotePending:0,pending:0,conflicts:0,error:error.message});throw error;}finally{migrationAuthorized=false;}}
  function schedule(){const localPending=context?context.getSongs().filter(isDirty).length:0;if(!token()){emit({phase:"unauthenticated",localPending:0,pending:0,error:null});return;}if(!hasConsent()){emit({phase:isOnline()?"needs-consent":"offline",localPending,pending:localPending+status.remotePending,error:null});return;}emit({phase:isOnline()?"pending":"offline",localPending,pending:localPending+status.remotePending,error:null});if(!isOnline())return;clearTimeout(timer);timer=setTimeout(()=>syncNow().catch(()=>{}),1200);}
  function classification(song,remote){const meta=metadata(song);if(!remote&&identityBlocked)return {status:"blocked_identity",reason:"remote_owner_unconfirmed"};if(!remote)return {status:"pending_upload",reason:meta.clientId?"missing_remote":"legacy_record"};const differs=!sameContent(song,remote.songData),dirty=isDirty(song),localVersion=Number(meta.serverVersion)||0;if(!differs)return {status:"synced",reason:meta.conflict?"stale_conflict_equivalent_content":meta.clientId?"content_equal":"legacy_adoptable"};if(meta.conflict)return {status:"conflict",reason:"stored_conflict"};if(!meta.contentHash)return {status:"conflict",reason:"missing_sync_base"};if(dirty&&remote.version>localVersion)return {status:"conflict",reason:"both_changed"};if(dirty)return {status:"pending_upload",reason:"local_changed"};if(remote.version>localVersion)return {status:"pending_download",reason:"remote_changed"};return {status:"conflict",reason:"fingerprint_mismatch"};}
  function diagnosticRows(){const songs=context?context.getSongs():[],matched=new Set(),rows=songs.map(song=>{const meta=metadata(song),remoteIndex=lastRemote.findIndex(item=>sameSong(song,item));if(remoteIndex>=0)matched.add(remoteIndex);const remote=remoteIndex>=0?lastRemote[remoteIndex]:null,result=classification(song,remote),rawLocal=wireSong(song),rawRemote=remote?.songData,comparison=lastComparisons.find(item=>String(item.localId)===String(song.id)||item.remoteClientId===remote?.clientId)||null;return {status:result.status,reason:result.reason,origin:meta.clientId?"synced_local_record":"legacy_local_record",localId:song.id??null,localClientId:meta.clientId||null,remoteClientId:remote?.clientId||null,title:String(song.title||""),artist:String(song.artist||""),localFingerprint:contentHash(song),remoteFingerprint:remote?contentHash(remote.songData):null,savedSyncFingerprint:meta.contentHash||null,localVersion:meta.serverVersion??null,remoteVersion:remote?.version??null,localUpdatedAt:song.updatedAt??null,remoteSongUpdatedAt:remote?.songData?.updatedAt??null,remoteRecordUpdatedAt:remote?.updatedAt??null,conflict:Boolean(meta.conflict),rawDiff:remote?structuralDiff(rawLocal,rawRemote):null,semanticDiff:remote?structuralDiff(musicalPayload(song),musicalPayload(remote.songData)):null,comparisonAtPull:comparison};});lastRemote.forEach((item,index)=>{if(!matched.has(index))rows.push({status:"pending_download",reason:"missing_local",origin:"cloud_record",localId:null,localClientId:null,remoteClientId:item.clientId,title:String(item.songData?.title||""),artist:String(item.songData?.artist||""),localFingerprint:null,remoteFingerprint:contentHash(item.songData),savedSyncFingerprint:null,localVersion:null,remoteVersion:item.version,localUpdatedAt:null,remoteSongUpdatedAt:item.songData?.updatedAt??null,remoteRecordUpdatedAt:item.updatedAt??null,conflict:false,rawDiff:null,semanticDiff:null,comparisonAtPull:null});});return rows;}
  function diagnostics(){const rows=diagnosticRows();return {generatedAt:new Date().toISOString(),syncState:{phase:status.phase,error:status.error,identityBlocked},remoteContract:lastRemoteContract,summary:{device:context?context.getSongs().length:0,cloud:lastRemote.length,deviceOnly:rows.filter(row=>row.status==="pending_upload"&&!row.remoteClientId).length,cloudOnly:rows.filter(row=>row.status==="pending_download"&&!row.localId).length,both:rows.filter(row=>row.localId&&row.remoteClientId).length,blockedIdentity:rows.filter(row=>row.status==="blocked_identity").length,conflicts:rows.filter(row=>row.status==="conflict").length,pendingUpload:rows.filter(row=>row.status==="pending_upload").length,pendingDownload:rows.filter(row=>row.status==="pending_download").length},server:serverAudit,rows};}
  async function refreshServerAudit(){try{serverAudit=await request("/diagnostics");return serverAudit;}catch(error){serverAudit={unavailable:true,error:error.code||"audit_unavailable"};return serverAudit;}}
  function markBackupReady(){if(!setOwnerFlag(BACKUP_KEY,true))return false;emit();return true;}
  function deferMigration(){emit({phase:"needs-consent",error:null});}
  function initialize(value){context=value;emit({local:context.getSongs().length});global.appAuth.subscribe(state=>{authenticated=Boolean(state.authenticated);const userId=authenticated&&state.user?.id;if(!userId){lastUserId=null;migrationCandidate=false;identityBlocked=false;emit({phase:"unauthenticated",remote:0,pending:0,localPending:0,remotePending:0,conflicts:0,error:null});return;}if(userId===lastUserId){emit();return;}lastUserId=userId;const ownerState=context.activateOwner?context.activateOwner(userId):null;if(ownerState){migrationCandidate=Boolean(ownerState.migrationCandidate);context.setSongs(ownerState.songs);context.render();}pull().then(result=>{if(hasConsent()&&result.status?.localPending)schedule();}).catch(()=>{if(migrationCandidate)emit({phase:"needs-consent",error:null});});});global.addEventListener?.("online",()=>{emit({phase:"pending",error:null});if(hasConsent())schedule();else pull().catch(()=>{});});global.addEventListener?.("offline",()=>emit({phase:"offline",error:null}));}
  function subscribe(listener){listeners.add(listener);listener(status);return ()=>listeners.delete(listener);}
  function getStatus(){return status;}
  global.librarySync=Object.freeze({consentKey:CONSENT_KEY,initialize,pull,review,syncNow,schedule,merge,prepared,wireSong,musicalPayload,contentHash,sameContent,structuralDiff,normalizeRemoteResponse,inspect,diagnostics,refreshServerAudit,markBackupReady,deferMigration,subscribe,getStatus});
})(window);
