const assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const {chromium}=require('playwright'),root=path.resolve(__dirname,'..');
const api='https://simplificandocifras-production.up.railway.app/api';
const executablePath=[process.env.BROWSER_EXECUTABLE,'C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(x=>x&&fs.existsSync(x));
const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname,file=path.resolve(root,pathname==='/'?'index.html':decodeURIComponent(pathname.slice(1)));if(!file.startsWith(root)||!fs.existsSync(file)||fs.statSync(file).isDirectory())return res.writeHead(404).end();const types={'.html':'text/html','.js':'application/javascript','.css':'text/css','.png':'image/png'};res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'});fs.createReadStream(file).pipe(res);});
const generated={schemaVersion:2,titulo:'<img src=x onerror=alert(1)>Canção',artista:'Artista',tom:'Dm',confianca:'media',observacoes:[],harmonicSummary:{blocos:[{acordes:['Dm','Bb','C'],repeticoes:2,fraseGuia:'Frase autorizada',secao:'Refrão'}]},fullChordSheet:{visibility:'private',source:'user_text',content:'Dm Bb C\nFrase autorizada',sections:[]}};
const generatedWithoutSource={schemaVersion:2,titulo:'<svg onload=alert(1)>Sem fonte',artista:'Artista',tom:'D',confianca:'media',observacoes:['Gerado somente por IA; exige revisão humana.'],harmonicSummary:{blocos:[{acordes:['Bm','A','G'],repeticoes:null,fraseGuia:null,secao:'Verso'}]},fullChordSheet:null};
const candidates=[
 {providerId:'licensed',sourceId:'one',sourceName:'Fonte <b>Um</b>',sourceUrl:'https://licensed.example/one',title:'Canção <script>alert(1)</script>',artist:'Artista A'},
 {providerId:'licensed',sourceId:'two',sourceName:'Fonte Dois',sourceUrl:'https://licensed.example/two',title:'Canção',artist:'Artista B'}
];
(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const browser=await chromium.launch({headless:true,executablePath}),context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),page=await context.newPage();
 await page.addInitScript(()=>{const auth={initialize:async()=>({authenticated:true}),subscribe:()=>()=>{},getState:()=>({authenticated:true}),getAccessToken:()=>'test-token'};Object.defineProperty(window,'appAuth',{get:()=>auth,set:()=>{}});window.alert=()=>{window.__alertCalled=true;};});
 await page.route('https://fonts.googleapis.com/**',r=>r.fulfill({status:200,contentType:'text/css',body:''}));await page.goto(`http://127.0.0.1:${server.address().port}/`,{waitUntil:'domcontentloaded'});
 try{let searchPayload,generationPayload;
  await page.route(`${api}/music-sources/search`,r=>{searchPayload=r.request().postDataJSON();return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({candidates})});},{times:1});
  await page.route(`${api}/resumo-harmonico`,r=>{generationPayload=r.request().postDataJSON();return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify(generated)});},{times:1});
  await page.getByRole('button',{name:'Gerar com IA',exact:true}).click();
  assert.deepEqual(await page.getByRole('tab').allTextContents(),['🔎 Busca por IA','📁 Arquivo ou foto']);assert.equal(await page.getByRole('tab',{name:/Busca por IA/}).getAttribute('aria-selected'),'true');
  const dialog=page.locator('#ai-summary-overlay'),dialogSubmit=dialog.locator('[data-ai-submit]');assert.equal(await dialogSubmit.innerText(),'Gerar com IA');assert.equal(await dialog.getByRole('button',{name:'Buscar com IA'}).count(),0);
  await dialogSubmit.click();assert.match(await page.locator('[data-ai-status]').innerText(),/Informe o título/);
  await page.getByLabel('Título da música').fill('Canção');await page.getByLabel('Artista',{exact:true}).fill('Artista');await dialogSubmit.click();await page.getByText('Encontramos mais de uma versão').waitFor();
  assert.deepEqual(searchPayload,{titulo:'Canção',artista:'Artista'});assert.equal(generationPayload,undefined);assert.equal(await page.evaluate(()=>Boolean(window.__alertCalled)),false);assert.equal(await page.locator('.ai-summary-candidate script').count(),0);
  await page.getByRole('button',{name:/Canção.*Artista B.*Fonte Dois/}).click();await page.getByText('Revisar resumo harmônico',{exact:true}).waitFor();
  assert.deepEqual(generationPayload,{tipo:'pesquisa',titulo:'Canção',artista:'Artista',sourceProvider:'licensed',sourceId:'two'});assert.equal(await page.evaluate(()=>localStorage.getItem('sc_song_editor_drafts_v1')),null);assert.equal(await page.getByLabel('Título',{exact:true}).inputValue(),'img src=x onerror=alert(1)Canção');await page.getByRole('button',{name:'Cancelar',exact:true}).click();
  let fallbackPayload;await page.route(`${api}/music-sources/search`,r=>r.fulfill({status:200,contentType:'application/json',body:'{"candidates":[]}'}),{times:1});await page.route(`${api}/resumo-harmonico`,r=>{fallbackPayload=r.request().postDataJSON();return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify(generatedWithoutSource)});},{times:1});
  await page.getByRole('button',{name:'Gerar com IA',exact:true}).click();const fallbackDialog=page.locator('#ai-summary-overlay');await fallbackDialog.getByLabel('Título da música').fill('Sem fonte');await fallbackDialog.getByLabel('Artista',{exact:true}).fill('Artista');await fallbackDialog.locator('[data-ai-submit]').click();await page.getByText('Revisar resumo harmônico',{exact:true}).waitFor();assert.deepEqual(fallbackPayload,{tipo:'pesquisa',titulo:'Sem fonte',artista:'Artista',modoGeracao:'conhecimento_modelo'});assert.equal(await page.evaluate(()=>localStorage.getItem('sc_song_editor_drafts_v1')),null);assert.equal(await page.getByLabel('Letra + Cifras',{exact:true}).count(),0);assert.equal(await page.getByLabel('Título',{exact:true}).inputValue(),'svg onload=alert(1)Sem fonte');assert.equal(await page.evaluate(()=>Boolean(window.__alertCalled)),false);await page.getByRole('button',{name:'Cancelar',exact:true}).click();
  let errorFallbackPayload;await page.route(`${api}/music-sources/search`,r=>r.fulfill({status:503,contentType:'application/json',body:'{"erro":{"codigo":"fonte_indisponivel","mensagem":"x"}}'}),{times:1});await page.route(`${api}/resumo-harmonico`,r=>{errorFallbackPayload=r.request().postDataJSON();return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify(generatedWithoutSource)});},{times:1});
  await page.getByRole('button',{name:'Gerar com IA',exact:true}).click();await page.locator('#ai-summary-overlay').getByLabel('Título da música').fill('Busca falhou');await page.locator('#ai-summary-overlay [data-ai-submit]').click();await page.getByText('Revisar resumo harmônico',{exact:true}).waitFor();assert.deepEqual(errorFallbackPayload,{tipo:'pesquisa',titulo:'Busca falhou',modoGeracao:'conhecimento_modelo'});await page.getByRole('button',{name:'Cancelar',exact:true}).click();
  let uploadRequest;await page.route(`${api}/resumo-harmonico`,r=>{uploadRequest=r.request();return r.abort('failed');},{times:1});await page.getByRole('button',{name:'Gerar com IA',exact:true}).click();await page.getByRole('tab',{name:/Arquivo ou foto/}).click();const input=page.locator('input[type=file]');assert.equal(await input.getAttribute('multiple'),'');await input.setInputFiles([{name:'pagina-1.png',mimeType:'image/png',buffer:Buffer.from('fixture')},{name:'cifra.txt',mimeType:'text/plain',buffer:Buffer.from('Dm Bb C')}]);await page.getByRole('button',{name:'Gerar resumo'}).click();await page.waitForTimeout(80);assert.match(uploadRequest.headers()['content-type'],/multipart\/form-data/);assert.match(uploadRequest.postData(),/pagina-1\.png/);assert.match(uploadRequest.postData(),/cifra\.txt/);
  console.log('ai-harmonic-summary-ui.test.js: OK (busca, seleção, fallback automático, rascunho, XSS e arquivo/foto)');
 }finally{await context.close();await browser.close();server.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
