const assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const {chromium}=require('playwright'),root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const file=path.resolve(root,new URL(req.url,'http://localhost').pathname.slice(1)||'index.html');if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile())return res.writeHead(404).end();res.writeHead(200,{'Content-Type':({'.html':'text/html','.js':'application/javascript','.css':'text/css','.png':'image/png','.webmanifest':'application/manifest+json'})[path.extname(file)]||'application/octet-stream'});fs.createReadStream(file).pipe(res);});
(async()=>{let browser;try{
  await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
  const page=await (await browser.newContext({serviceWorkers:'block'})).newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/api/**',r=>r.fulfill({json:{enabled:false,songs:[],events:[],bands:[]}}));await page.route('https://fonts.googleapis.com/**',r=>r.fulfill({body:'',contentType:'text/css'}));
  await page.goto(`http://127.0.0.1:${server.address().port}/`,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.roudyAssistant&&loginGateAuthReady);
  await page.evaluate(()=>{continueWithoutLogin();musicas.push({id:'voice-test',title:'Teste de voz',artist:'Teste',key:'C',blocos:Array.from({length:25},()=>({l:'Letra de teste',c:'C G Am F'}))});openDetail('voice-test');});
  const run=command=>page.evaluate(command=>roudyAssistant.run(command),command);
  assert.equal((await run('abrir metrônomo')).ok,true);assert.equal(await page.locator('#tools-metronome').count(),0);
  const save=page.locator('#detail-save-changes');assert.equal(await save.isVisible(),false);
  await page.evaluate(()=>transpose(1));assert.equal(await save.isVisible(),true);await page.evaluate(()=>transpose(-1));assert.equal(await save.isVisible(),false,'desfazer esconde botão');
  await page.evaluate(()=>{transpose(2);selectCapo(3);studyMetronome.setBpm(108);studyMetronome.setMeter('3/4');adjustStageScrollSpeed(1);});
  assert.equal(await save.isVisible(),true);await save.click();assert.equal(await save.isVisible(),false);
  await page.evaluate(()=>{closeDetail();openDetail('voice-test');});
  assert.deepEqual(await page.evaluate(()=>({tom:currentSemitones,capo:selectedCapo,bpm:studyMetronome.getBpm(),meter:studyMetronome.getMeter()})),{tom:2,capo:3,bpm:108,meter:'3/4'});
  await page.evaluate(()=>{stageDetailVideoSongs(musicas.map(s=>s.id==='voice-test'?{...s,youtubeVideoId:'test-video'}:s));});assert.equal(await save.isVisible(),true);
  assert.equal(await page.evaluate(()=>musicas.find(s=>s.id==='voice-test').youtubeVideoId||null),null,'vídeo fica em rascunho');
  await page.evaluate(()=>stageDetailVideoSongs(musicas));assert.equal(await save.isVisible(),false,'vídeo desfeito remove pendência');
  await page.evaluate(()=>{studyMetronome.setBpm(111);closeDetail();openDetail('voice-test');});assert.equal(await page.evaluate(()=>studyMetronome.getBpm()),108,'sem salvar descarta ajuste temporário');
  await run('metrônomo em noventa');assert.equal(await page.evaluate(()=>studyMetronome.getBpm()),90);
  await run('compasso seis por oito');assert.equal(await page.evaluate(()=>studyMetronome.getMeter()),'6/8');
  assert.equal((await run('iniciar rolagem automática')).ok,true);assert.equal((await run('ativar rolagem automática')).ok,true);assert.equal(await page.evaluate(()=>scrollTimer!==null),true);
  await run('interromper rolagem automática');assert.equal(await page.evaluate(()=>scrollTimer),null);
  await run('mudar cor das cifras para azul');assert.equal(await page.evaluate(()=>loadAppSettings().chordColor),'blue');
  await run('capotraste na casa três');assert.equal((await run('capotraste na casa treze')).ok,false);
  await run('abrir eventos');assert.equal(await page.locator('#view-detail').isVisible(),false);
  await run('abrir Teste de voz');assert.equal(await page.locator('#view-detail').isVisible(),true);
  await page.evaluate(()=>{openAccountModal();roudyAssistant.updateLaunchVisibility();});
  await page.waitForFunction(()=>document.getElementById('app-assistant-floating').hidden&&document.getElementById('song-assistant-launch').hidden);
  for(const menu of ['openAppSettings','openLanguageSettings','openAppearanceSettings','openToolsMenu','openProfileSettings']){
    await page.evaluate(menu=>window[menu](),menu);
    assert.equal(await page.locator('#app-assistant-floating').isVisible(),false,menu);
    assert.equal(await page.locator('#song-assistant-launch').isVisible(),false,menu);
  }
  await page.evaluate(()=>{closeModal();roudyAssistant.updateLaunchVisibility();});assert.equal(await page.locator('#song-assistant-launch').isVisible(),true,'reaparece fora da conta');
  await page.evaluate(async()=>{await openAccountModal();openProfileSettings();});
  await page.locator('#profile-location').fill('São Paulo, SP');
  assert.equal(await page.getByLabel('Selecione um nome de usuário único',{exact:true}).isVisible(),true,'campo aparece mesmo para convidado');
  assert.equal(await page.locator('input[name="profile-instruments"][value="Vocalista"]').isVisible(),false,'lista inicia recolhida');
  await page.locator('.profile-instruments-dropdown summary').click();
  await page.locator('input[name="profile-instruments"][value="Vocalista"]').check();
  await page.locator('input[name="profile-instruments"][value="Guitarrista"]').check();
  await page.getByRole('button',{name:'Salvar perfil',exact:true}).click();
  await page.evaluate(()=>openProfileSettings());
  assert.equal(await page.locator('#profile-location').inputValue(),'São Paulo, SP');
  assert.equal(await page.locator('input[name="profile-instruments"]:checked').count(),2);
  assert.equal(await page.locator('#app-assistant-floating').isVisible(),false,'assistente permanece oculto no perfil');
  await page.locator('#profile-location').fill('');
  await page.locator('.profile-instruments-dropdown summary').click();
  await page.locator('input[name="profile-instruments"][value="Vocalista"]').uncheck();
  await page.locator('input[name="profile-instruments"][value="Guitarrista"]').uncheck();
  await page.getByRole('button',{name:'Salvar perfil',exact:true}).click();await page.evaluate(()=>openProfileSettings());
  assert.equal(await page.locator('#profile-location').inputValue(),'');
  assert.equal(await page.locator('input[name="profile-instruments"]:checked').count(),0,'remoção dos campos também é salva');
  assert.deepEqual(errors,[]);console.log('assistant-context-ui.test.js: OK (contexto real, BPM falado, compasso, rolagem, cor, capotraste e navegação)');
}finally{await browser?.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
