const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const sandbox = { window: {} };
for (const file of ['assistant-actions.js','assistant-action-manager.js','assistant-action-runtime.js','assistant-dialogue.js','assistant-sequences.js']) vm.runInNewContext(fs.readFileSync(`js/${file}`,'utf8'),sandbox);
const api = sandbox.window;
const normalize = text => String(text).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/^coloque /,'colocar ').replace(/^ajuste /,'ajustar ').replace(/^salve /,'salvar ');
const numbers = text => text.replace('cento e vinte e cinco','125').replace(/\bdois\b/g,'2');
(async()=>{
  let context = {ownerId:'A',authSubject:'A',libraryOwner:'A',ready:true,screen:'song',songOpen:true,songId:'1',eventId:null,itemId:null,canEditSong:true,canAccessEvent:true,canManageEvent:true,editorOpen:false,dialogueScope:'song'};
  let values={capo:0,semitones:0,bpm:72,meter:'4/4',chordColor:'coral',language:'pt-BR',theme:'dark',scale:100,highContrast:false,colorBlind:false},saved=[],calls=[],failBpm=false,holdBpm=null;
  const tool={getBpm:()=>values.bpm,getMeter:()=>values.meter,setBpm:async value=>{calls.push('bpm');if(holdBpm)await holdBpm;if(!failBpm)values.bpm=value;},setMeter:value=>{values.meter=value;},isPlaying:()=>false};
  const host={context:()=>({...context}),capo:()=>values.capo,semitones:()=>values.semitones,selectCapo:v=>{calls.push('capo');values.capo=v;},transpose:d=>{calls.push('tom');values.semitones+=d;},resetTranspose:()=>{values.semitones=0;},metronome:()=>tool,isDirty:()=>true,saveSong:async()=>{calls.push('save');saved.push({...values,scope:context.eventId?'event-personal':'playlist-personal'});return {ok:true,scope:saved.at(-1).scope};},settings:()=>({...values}),updateSettings:changes=>{Object.assign(values,changes);return {ok:true};},settingsApplied:(k,v)=>values[k]===v,showMetronome(){},legacy:()=>({ok:false,message:'Unknown'})};
  const catalog=api.roudyAssistantActions.create({songMatches:()=>[],eventDate:()=>null,classify:()=>null});
  const native=api.roudyActionManager.create({catalog,runtime:api.roudyAssistantRuntime.create(host),normalize,numbers});
  const sequence=api.roudyAssistantSequences.create({manager:native,context:host.context,normalize,snapshot:()=>({...values}),restore:async(k,v,guard)=>{guard();values[k]=v;}});
  const dialogue=api.roudyAssistantDialogue.create({manager:sequence,context:host.context,normalize,numbers});
  const run=(text,opts)=>dialogue.run(text,opts);
  for(const command of ['capotraste 2 e bpm 90 e compasso 7 por 8','capotraste 2 e bpm 999','capotraste 2 e excluir musica','capotraste 2 e abrir eventos','capotraste 2 e não bpm 90','capotraste 2 e bpm 90 e tema claro e cor da cifra verde','capotraste 2 e capotraste 3','salvar e capotraste 2','cor da cifra verde e salvar','capotraste 2;','bpm 90,5 e capotraste 2','capotraste 2 e iniciar metronomo 90']){assert.equal((await run(command)).ok,false,command);assert.deepEqual(calls,[],command);}
  const combined='coloque capotraste na casa dois, ajuste metronomo em cento e vinte e cinco e salve as alteracoes';
  assert.equal((await run(combined,{requestId:'batch-1'})).completed,3);assert.deepEqual(calls,['capo','bpm','save']);assert.equal(values.bpm,125);assert.equal(saved.length,1);
  assert.equal((await run(combined,{requestId:'batch-1'})).duplicate,true);assert.equal(saved.length,1);
  assert.equal((await run('desfaça a última alteração')).ok,true);assert.equal(values.capo,0);assert.equal(values.bpm,72);assert.equal(saved.at(-1).capo,2,'undo is only a draft, never rewrites saved data');
  assert.equal((await run('desfazer')).ok,false,'one-shot history');
  await run('mudar cor');assert.equal((await run('azul')).ok,true);await run('desfazer');assert.equal(values.chordColor,'coral','parameter reply also records undo');
  await run('mudar cor');assert.equal((await run('capotraste 3 e bpm 100')).completed,2);assert.equal(dialogue.getPending(),null);await run('desfazer');
  failBpm=true;calls=[];const partial=await run('capotraste 4 e bpm 95 e salvar');assert.equal(partial.status,'error');assert.equal(partial.completed,1);assert.deepEqual(calls,['capo','bpm']);assert.equal(saved.length,1);await run('desfazer');assert.equal(values.capo,0);failBpm=false;
  await run('capotraste 5');values.capo=6;assert.equal((await run('desfazer')).ok,false);assert.equal(values.capo,6,'manual edit preserved');
  await run('bpm 88');context.eventId='event';context.itemId='item';assert.equal((await run('desfazer')).ok,false,'playlist history cannot affect event');
  values.capo=0;values.bpm=72;await run('capotraste 2 e bpm 90 e salvar');assert.equal(saved.at(-1).scope,'event-personal');await run('desfazer');assert.equal(values.capo,0);assert.equal(saved.at(-1).capo,2);
  await run('bpm 100');context.screen='home';sequence.sync();context.screen='song';assert.equal((await run('desfazer')).ok,false,'leaving and returning invalidates history');
  await run('capotraste 2');context.ownerId='B';context.authSubject='B';context.libraryOwner='B';assert.equal((await run('desfazer')).ok,false);assert.equal(sequence.getLastResult().ok,false);
  let release;holdBpm=new Promise(resolve=>release=resolve);calls=[];const pending=run('capotraste 3 e bpm 105 e salvar');await new Promise(resolve=>setImmediate(resolve));assert.equal((await sequence.run('capotraste 8')).ok,false,'whole batch locked');context.songId='other';release();assert.equal((await pending).ok,false);assert.ok(!calls.includes('save'));holdBpm=null;
  context.songId='1';context.editorOpen=true;calls=[];assert.equal((await run('capotraste 2 e bpm 90')).ok,false);assert.deepEqual(calls,[]);context.editorOpen=false;
  context.canEditSong=false;assert.equal((await run('capotraste 2 e bpm 90')).ok,false);context.canEditSong=true;
  assert.equal((await run('cor da cifra verde e tema claro')).completed,2);values.scale=110;await run('desfazer');assert.equal(values.chordColor,'coral');assert.equal(values.theme,'dark');assert.equal(values.scale,110,'unrelated change preserved');
  await run('tema claro');await run('mudar cor');assert.equal((await run('desfazer')).ok,true,'undo cancels pending slot question');assert.equal(dialogue.getPending(),null);
  calls=[];let manualRelease;holdBpm=new Promise(resolve=>manualRelease=resolve);
  const manualPending=run('capotraste 4 e bpm 95 e salvar');await new Promise(resolve=>setImmediate(resolve));values.capo=7;manualRelease();
  const interrupted=await manualPending;assert.equal(interrupted.ok,false);assert.equal(interrupted.completed,2);assert.ok(!calls.includes('save'),'intervening manual edit stops final save');assert.equal((await run('desfazer')).ok,false);assert.equal(values.capo,7);holdBpm=null;
  let restoration=0;
  const failingUndo=api.roudyAssistantSequences.create({manager:native,context:host.context,normalize,snapshot:()=>({...values}),restore:async(k,v)=>{if(++restoration===2)throw new Error('storage failure');values[k]=v;}});
  await failingUndo.run('capotraste 8 e bpm 100');const undone=await failingUndo.run('desfazer');assert.equal(undone.status,'error');assert.equal(undone.restored,1);assert.equal((await failingUndo.run('desfazer')).ok,false,'failed restore cannot be replayed silently');
  console.log('assistant-sequences: OK (preflight, numeric conjunctions, partial failure, duplicate, locking, dialogue, scope and safe undo)');
})().catch(error=>{console.error(error);process.exitCode=1;});
