const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const html = fs.readFileSync(path.resolve(__dirname, "..", "index.html"), "utf8");
const eventDetailCss = fs.readFileSync(path.resolve(__dirname, "..", "js", "event-detail-refactor.css"), "utf8");
const notificationCenterJs = fs.readFileSync(path.resolve(__dirname, "..", "js", "notification-center.js"), "utf8");
const colorPreviewCss = fs.readFileSync(path.resolve(__dirname, "..", "css", "roudy-color-system-preview.css"), "utf8");
assert.match(html, /roudy-color-system-preview\.css\?v=13/);
assert.match(html, /id="event-chat-context"/);
assert.match(html, /function installEventMessageContext/);
assert.match(html, /function openEventChatContext/);
assert.match(html, /Apagar para mim/);
assert.match(html, /Apagar para todos/);
assert.match(html, /Respondendo a \$\{eventEsc/);
assert.doesNotMatch(html, /eventChatButton\('Copiar'/);
assert.match(colorPreviewCss, /#view-sd \.event-detail-back\{color:var\(--text-primary\)\}/);
assert.doesNotMatch(colorPreviewCss, /#view-sd \.event-stage-entry[,{]/);
assert.match(colorPreviewCss, /#view-sd\{background:var\(--ui-background\)/);
assert.match(colorPreviewCss, /#view-sd \.detail-content\{background:var\(--ui-background\)\}/);
assert.doesNotMatch(colorPreviewCss, /\.playlist-ai-card\s*\{/);
assert.doesNotMatch(colorPreviewCss, /\.playlist-ai-action--primary\s*\{/);
assert.match(colorPreviewCss, /--roudy-electric-blue:#0789E7/);
assert.match(colorPreviewCss, /--roudy-stage-gold:#D6A83A/);
assert.match(colorPreviewCss, /--ui-background:#0B0B0C/);
assert.match(colorPreviewCss, /--text-secondary:#A1A1A6/);
assert.match(colorPreviewCss, /--semantic-success:#31C98B/);
assert.match(colorPreviewCss, /--semantic-danger:#F06464/);
assert.doesNotMatch(colorPreviewCss, /#(?:2f80ed|2563eb|3b82f6|60a5fa|65a3ff|69a8ff|58a6ff|1d4ed8|0a84ff|f4c430|f6c945|ffd400|f4d45d|d89d00)\b/i);
assert.match(html, /id="primary-tabs" role="tablist"/);
assert.match(html, /class="tab-indicator" aria-hidden="true"/);
assert.match(html, /id="tab-musicas"[\s\S]*?aria-selected="true"[\s\S]*?>Playlist<\/span>/);
assert.match(html, /id="tab-setlists"[\s\S]*?aria-selected="false"[\s\S]*?>Eventos<\/span>/);
assert.match(html, /id="tab-medley"[\s\S]*?aria-selected="false"[\s\S]*?>Medley<\/span>/);
assert.match(html, /--active-segment[\s\S]*?transition:transform 220ms/);
assert.match(html, /event-model\.js/);
assert.match(html, /event-repository\.js/);
assert.match(html, /event-collaboration-client\.js/);
assert.match(html, /event-chat\.js/);
assert.match(html, /id="event-chat-view"/);
assert.match(html, /aria-label="Personalizar fundo do chat"/);
assert.match(html, /EVENT_CHAT_BACKGROUND_KEY/);
assert.match(html, /EVENT_CHAT_BACKGROUNDS=\['black','blue','warm','graphite'\]/);
assert.match(html, /function openChatAppearance/);
assert.match(eventDetailCss, /#event-chat-view\.event-chat-view\{background:#000/);
assert.match(eventDetailCss, /event-message\.mine \.event-message-bubble\{background:#2f80ed;color:#fff\}/);
assert.match(eventDetailCss, /event-message-bubble\{background:#e7e7eb;color:#15161a/);
assert.match(eventDetailCss, /event-message-stack\{position:relative/);
assert.match(eventDetailCss, /event-message-reply-context\{display:flex/);
assert.match(eventDetailCss, /event-message-reply-quote\{display:block[^}]*background:transparent/);
assert.match(eventDetailCss, /event-message-reactions\{position:absolute/);
assert.doesNotMatch(eventDetailCss, /event-message:has\(\.event-message-reply-quote\) \.event-message-bubble/);
assert.match(html, /stack\.appendChild\(context\)/);
assert.match(html, /stack\.appendChild\(reactions\)/);
assert.match(html, /function eventChatMessagesShareGroup/);
assert.match(html, /event-chat-time-divider/);
assert.match(html, /event-message-reply-label/);
assert.doesNotMatch(html, /className='event-message-controls'/);
assert.match(eventDetailCss, /event-message\.is-group-continuation/);
assert.match(notificationCenterJs, /notification-center-page/);
assert.match(notificationCenterJs, /notification-period/);
assert.match(notificationCenterJs, /relativeDate/);
assert.match(notificationCenterJs, /getRoudyNotificationItems==='function'/);
assert.match(html, /function getRoudyNotificationItems/);
assert.match(html, /function openRoudyNotification/);
assert.match(html, /id="user-invitations-button"[^>]*onclick="eventUserInvites\.openInbox\(\)"/);
assert.match(eventDetailCss, /notification-center-overlay/);
assert.match(html, /function eventNoticePeriod/);
assert.match(html, /notification-row notification-row-static/);
assert.match(html, /function eventAvatarPaletteClass/);
assert.match(html, /event-detail-refactor\.css\?v=4/);
assert.match(html, /id="event-chat-avatar"/);
assert.match(eventDetailCss, /event-message\.system\.mine \.event-message-bubble/);
assert.match(eventDetailCss, /roudy-avatar-tone-0/);
assert.match(eventDetailCss, /roudy-avatar-tone-5/);
assert.doesNotMatch(eventDetailCss, /radial-gradient\(circle at 76% 24%/);
assert.match(html, /id="event-chat-fab"/);
assert.match(html, /id="event-chat-fab"[\s\S]*?id="event-notification-button"/);
assert.match(html, /event-chat-header-button\[hidden\]/);
assert.match(html, /changeEventOfficialKey/);
assert.match(html, /eventModel\.canEditShared\(event,actor\.id\)/);
assert.match(html, /openStageFromEvent/);
assert.doesNotMatch(html, /Eventos disponíveis offline/);
assert.doesNotMatch(html, />Postar<\/button>/);
assert.doesNotMatch(html, /Você lidera|class="event-sync-badge/);
assert.match(html, /async function syncEventsNow/);
assert.match(html, /eventRepository\.reconcileRemote\(setlists,remote\)/);
assert.match(html, /visibilitychange[\s\S]*?eventMigrationCandidate[\s\S]*?syncEventsNow\(true\)/);
assert.match(html, /if\(tab==='setlists'\)[\s\S]*?syncEventsNow\(true\)/);
const silentMigration = html.slice(html.indexOf("async function migrateLegacyEventsInBackground"), html.indexOf("// carrega dados salvos"));
assert.doesNotMatch(silentMigration, /exportarBiblioteca|libraryExporter|link\.click|download=/, "migração silenciosa não pode baixar arquivos");
assert.doesNotMatch(html, /id="fs-location"/);
assert.doesNotMatch(html, /id="fs-description"/);
assert.doesNotMatch(html, /Somente o líder marcado poderá alterar músicas/);
assert.doesNotMatch(html, /Compartilhamento Pendente|● Sincronizado/);
assert.doesNotMatch(html, /Disponível offline · sincronização pendente/);
assert.match(html, /id="event-song-edit-layer"/);
assert.match(html, /Cifra \/ resumo \/ letra/);
assert.match(html, /id="event-song-edit-key"/);
assert.match(html, /id="event-song-edit-capo"/);
assert.match(html, /id="event-song-edit-view"/);
assert.match(html, /data-edit-song-view="summary"/);
assert.match(html, /data-edit-song-view="chords"/);
assert.match(html, /data-edit-song-view="combined"/);
assert.match(html, /data-edit-song-view="lyrics"/);
assert.match(html, /stepEventSongEditKey/);
assert.match(html, /stepEventSongEditCapo/);
assert.match(html, /function eventSongEditTextForView/);
assert.match(html, /eventSongEditDraft\.viewTexts\[eventSongEditDraft\.activeView\]=text\.value/);
assert.match(html, /event-song-edit-text-label/);
assert.match(html, /Cifra \/ resumo \/ letra — /);
assert.match(html, /id="event-song-edit-notes"/);
assert.match(html, /eventModel\.applySharedEdit\(event,draft\.itemId/);
assert.doesNotMatch(html, /const keyControl=/);
assert.doesNotMatch(html, /event-scope-badge/);
assert.match(html, /id="event-notification-button"/);
assert.match(html, /event-notification-badge/);
assert.match(html, /EVENT_NOTICE_READ_KEY/);
assert.match(html, /openEventNotifications/);
assert.match(html, /simpleSongEditorFields/);
assert.match(html, /eventSongVariant/);
assert.match(html, /Somente o líder pode editar o repertório oficial/);
assert.match(html, /eventModel\.canEditShared/);
assert.match(html, /openEventLeadershipTransfer/);
assert.match(html, /confirmEventLeadershipTransfer/);
assert.match(html, /eventCollaboration\.transferLeadership/);
assert.doesNotMatch(html, /class="event-leadership-action"/, 'transferência não deve ocupar espaço permanente na página');
assert.match(html, /Convidar Integrante/);
assert.match(eventDetailCss, /\.event-invite-primary \.event-invite-check\{background:#2f80ed;color:#fff\}/);
assert.match(html, /navigator\.share\(\{title:'Convite para '/);
assert.match(html, /acceptPendingEventInvitation/);
assert.doesNotMatch(html, /id="event-member-id"|name="event-leader-id"/);
assert.match(html, /function openEventMoreActions[\s\S]*?>Editar evento</);
assert.match(html, /function editSetlistById\(id\)\{\s*openEventInfoSheet\(id\);\s*\}/, 'Editar evento no menu de três pontos deve abrir o sheet atual');
assert.match(html, /function openEventMoreActions[\s\S]*?>Excluir evento</);
assert.doesNotMatch(html, /<div class="btn-row" style="margin-top:16px;">[\s\S]*?✏️ Editar/, 'ações administrativas não ficam em uma barra permanente');
assert.match(html, /event-repertoire-meta">Tom \$\{eventEsc\(officialKey\)\} · Capo/);
assert.match(html, /class="event-reference-actions"/);
assert.match(html, /class="event-reference-admin"/);
assert.match(html, /openEventSongMenu/);
assert.match(html, /Ir para a página de estudo/);
assert.match(html, /Editar na minha versão/);
assert.match(html, /Editar na versão da banda/);
assert.match(html, /Remover do evento/);
assert.match(html, />Música<\/span>/);
assert.match(html, />Ordenar<\/span>/);
assert.match(html, />Editar<\/span>/);
assert.match(html, /function openEventAddSongs/);
assert.match(html, /O que você gostaria de adicionar\?/);
assert.match(html, /function openEventOrderSheet/);
assert.match(html, /Pressione e arraste pelo ícone à direita/);
assert.match(html, /function openEventInfoSheet/);
assert.match(html, /id="event-admin-date"/);
assert.match(html, /id="event-admin-time"/);
assert.match(html, /id="event-admin-location"/);
assert.match(html, /id="event-admin-description"/);
assert.match(html, /event-reference-actions[\s\S]*?Modo Palco[\s\S]*?event-section-title--repertoire/, 'ações e Modo Palco aparecem antes do repertório conforme a referência aprovada');
assert.match(html, /createPoll/);
assert.match(html, /eventRepository\.load/);
const authBootstrap = html.slice(html.indexOf("appAuth.subscribe(async state=>{"), html.indexOf("librarySync.initialize"));
assert.doesNotMatch(authBootstrap, /state\.user\.id\)===String\(appCurrentUser\.id\)/, "identidade histórica igual à conta não pode pular a convergência");
assert.match(authBootstrap, /activateOwner[\s\S]*listEvents[\s\S]*reconcileRemote/, "bootstrap autenticado precisa ativar owner, consultar e reconciliar Eventos");
assert.match(silentMigration, /uploadMigrationCandidates/, "migração precisa tratar falhas por Evento sem abortar o lote");
assert.match(silentMigration, /missing\.length[\s\S]*?eventBackgroundSyncReady=true;return/, "Evento legado inválido não pode bloquear a convergência normal");
assert.match(authBootstrap, /eventBackgroundSyncReady=true/, "bootstrap autenticado sempre habilita leitura remota após ativar o owner");
const automaticSync = html.slice(html.indexOf("async function syncEventsNow"), html.indexOf("const EVENT_NOTICE_READ_KEY"));
assert.match(automaticSync, /for\(const localEvent[\s\S]*?catch\(error\)[\s\S]*?listEvents/, "falha de um Evento não pode impedir GET e reconciliação dos demais");
console.log("event-ui-source.test.js: OK");
