const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const html = fs.readFileSync(path.resolve(__dirname, "..", "index.html"), "utf8");
assert.match(html, />🎵 Playlist</);
assert.match(html, />📅 Eventos</);
assert.match(html, /event-model\.js/);
assert.match(html, /event-repository\.js/);
assert.match(html, /event-collaboration-client\.js/);
assert.match(html, /event-chat\.js/);
assert.match(html, /id="event-chat-view"/);
assert.match(html, /id="event-chat-fab"/);
assert.match(html, /right:max\(18px,calc\(\(100vw - 720px\)\/2 \+ 18px\)\)/);
assert.match(html, /openStageFromEvent/);
assert.doesNotMatch(html, /Eventos disponíveis offline/);
assert.doesNotMatch(html, />Postar<\/button>/);
assert.doesNotMatch(html, /Você lidera|class="event-sync-badge/);
assert.match(html, /async function syncEventsNow/);
assert.match(html, /eventRepository\.reconcileRemote\(setlists,remote\)/);
assert.match(html, /visibilitychange[\s\S]*?eventMigrationCandidate[\s\S]*?syncEventsNow\(true\)/);
assert.match(html, /if\(tab==='setlists'\)[\s\S]*?syncEventsNow\(true\)/);
const silentMigration = html.slice(html.indexOf("async function migrateLegacyEventsInBackground"), html.indexOf("// carrega dados salvos"));
assert.doesNotMatch(silentMigration, /exportarBiblioteca|libraryExporter|link\.click|download=/, "migração silenciosa não pode baixar arquivos");
assert.doesNotMatch(html, /id="fs-location"/);
assert.doesNotMatch(html, /id="fs-description"/);
assert.doesNotMatch(html, /Somente o líder marcado poderá alterar músicas/);
assert.doesNotMatch(html, /Compartilhamento Pendente|● Sincronizado/);
assert.doesNotMatch(html, /Disponível offline · sincronização pendente/);
assert.match(html, /Pessoal — somente para mim/);
assert.match(html, /Compartilhada — todos do evento/);
assert.doesNotMatch(html, /event-scope-badge/);
assert.match(html, /id="event-notification-button"/);
assert.match(html, /event-notification-badge/);
assert.match(html, /EVENT_NOTICE_READ_KEY/);
assert.match(html, /openEventNotifications/);
assert.match(html, /simpleSongEditorFields/);
assert.match(html, /eventSongVariant/);
assert.match(html, /Somente o líder pode editar o repertório oficial/);
assert.match(html, /eventModel\.canEditShared/);
assert.match(html, /onclick="editSetlistById\('\$\{eventEsc\(event\.id\)\}'\)"[^>]*>✏️ Editar<\/button>/);
assert.match(html, /onclick="deleteSetlist\('\$\{eventEsc\(event\.id\)\}'\)"[^>]*>🗑️ Excluir<\/button>/);
assert.match(html, /createPoll/);
assert.match(html, /eventRepository\.load/);
const authBootstrap = html.slice(html.indexOf("appAuth.subscribe(async state=>{"), html.indexOf("librarySync.initialize"));
assert.doesNotMatch(authBootstrap, /state\.user\.id\)===String\(appCurrentUser\.id\)/, "identidade histórica igual à conta não pode pular a convergência");
assert.match(authBootstrap, /activateOwner[\s\S]*listEvents[\s\S]*reconcileRemote/, "bootstrap autenticado precisa ativar owner, consultar e reconciliar Eventos");
assert.match(silentMigration, /uploadMigrationCandidates/, "migração precisa tratar falhas por Evento sem abortar o lote");
assert.match(silentMigration, /missing\.length[\s\S]*?eventBackgroundSyncReady=true;return/, "Evento legado inválido não pode bloquear a convergência normal");
assert.match(authBootstrap, /eventBackgroundSyncReady=true/, "bootstrap autenticado sempre habilita leitura remota após ativar o owner");
const automaticSync = html.slice(html.indexOf("async function syncEventsNow"), html.indexOf("const EVENT_NOTICE_READ_KEY"));
assert.match(automaticSync, /for\(const localEvent[\s\S]*?catch\(error\)[\s\S]*?listEvents/, "falha de um Evento não pode impedir GET e reconciliação dos demais");
console.log("event-ui-source.test.js: OK");
