const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const html = fs.readFileSync(path.resolve(__dirname, "..", "index.html"), "utf8");
assert.match(html, />🎵 Playlist</);
assert.match(html, />📅 Eventos</);
assert.match(html, /event-model\.js/);
assert.match(html, /event-repository\.js/);
assert.match(html, /event-collaboration-client\.js/);
assert.match(html, /event-chat\.js/);
assert.match(html, /id="event-chat-view"/);
assert.match(html, /id="event-chat-fab"/);
assert.match(html, /left:max\(18px,calc\(\(100vw - 720px\)\/2 \+ 18px\)\)/);
assert.match(html, /Pessoal — somente para mim/);
assert.match(html, /Compartilhada — todos do evento/);
assert.doesNotMatch(html, /event-scope-badge/);
assert.match(html, /id="event-notification-button"/);
assert.match(html, /event-notification-badge/);
assert.match(html, /EVENT_NOTICE_READ_KEY/);
assert.match(html, /openEventNotifications/);
assert.match(html, /simpleSongEditorFields/);
assert.match(html, /eventSongVariant/);
assert.match(html, /Somente o líder/);
assert.match(html, /eventModel\.canEditShared/);
assert.match(html, /createPoll/);
assert.match(html, /eventRepository\.load/);
console.log("event-ui-source.test.js: OK");
