const assert = require("node:assert/strict");
const fs = require("node:fs");
const vm = require("node:vm");

const html = fs.readFileSync(require("node:path").resolve(__dirname, "..", "index.html"), "utf8");
const editorialCss = fs.readFileSync(require("node:path").resolve(__dirname, "..", "css", "editorial-typography.css"), "utf8");
const scripts = [...html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi)].map((match) => match[1]).filter((source) => source.trim());
assert.ok(scripts.length > 0, "index.html deve possuir scripts inline");
scripts.forEach((source, index) => new vm.Script(source, { filename: `index-inline-${index + 1}.js` }));
const musicPane = html.slice(html.indexOf('id="pane-musicas"'), html.indexOf('id="pane-setlists"'));
const topbar = html.slice(html.indexOf('id="app-topbar"'), html.indexOf('id="primary-tabs"'));
assert.doesNotMatch(musicPane, /class="search-bar"/, "a playlist não deve reservar espaço para uma busca permanente");
assert.match(topbar, /placeholder="Buscar músicas, artistas\.\.\."/);
assert.match(topbar, /id="topbar-search-mode"[^>]*hidden/);
assert.match(topbar, /onclick="openPlaylistSearch\(\)"/);
assert.match(topbar, /onclick="closePlaylistSearch\(\)"/);
assert.match(musicPane, /Encontre um vídeo para adicionar à sua playlist/);
assert.match(musicPane, /playlist-ai-card/, "a integração de IA deve permanecer disponível no hero da playlist");
assert.match(topbar, /onclick="openPhotoFileMenu\(\)"/, "a câmera deve permanecer acessível pelo cabeçalho (menu Foto/Arquivo)");
assert.match(html, /closeModal\(\);roudyCamera\.open\(\)/, "o menu Foto/Arquivo deve abrir a câmera");
assert.match(html, /function resolveHomeCardContext\(/, "o hero deve usar o motor contextual determinístico");
assert.match(musicPane, /id="playlist-context-editorial"[^>]*hidden/, "o hero deve manter a camada editorial opcional e oculta por padrão");
assert.match(html, /artDirection:'standard'/, "contextos cotidianos devem preservar a tipografia funcional");
assert.match(html, /typographyVariant:'condensed'/, "evento no dia deve possuir direção editorial condensada");
assert.match(html, /typographyVariant:'graphic'/, "mensagens expressivas devem possuir composição editorial gráfica");
assert.match(html, /typographyVariant:'numeric'/, "prazos reais devem possuir composição editorial numérica");
assert.match(html, /css\/editorial-typography\.css/, "o card deve carregar o sistema editorial compartilhado");
assert.match(editorialCss, /--font-display:/, "a voz editorial deve possuir token tipográfico próprio");
assert.match(editorialCss, /Barlow\+Condensed/, "a voz condensada deve usar uma família display real");
assert.match(editorialCss, /family=Bungee/, "a voz geométrica deve usar uma família display dedicada");
assert.match(editorialCss, /\.editorial-dimensional/, "o sistema deve incluir tratamento celebratório dimensional");
assert.match(editorialCss, /prefers-reduced-motion:reduce[\s\S]{0,500}playlist-ai-editorial-line/, "movimento editorial deve respeitar redução de movimento");
assert.match(html, /kind:'ai_search'/, "a pesquisa por IA deve permanecer acessível no contexto geral");
assert.match(html, /js\/ai\/camera-capture\.js/, "o módulo de captura por câmera deve ser carregado");
assert.match(musicPane, /aria-label="Limpar busca do YouTube"/);
assert.match(topbar, /aria-label="Limpar busca"[^>]*hidden/);
assert.doesNotMatch(html, /focusPlaylistSearch/, "o fluxo antigo da lupa deve ser removido");
const playlistSearchFlow = html.slice(html.indexOf('function openPlaylistSearch'), html.indexOf('function renderMusicas'));
assert.doesNotMatch(playlistSearchFlow, /scrollIntoView\(/, "a lupa do cabeçalho não deve rolar a página");
console.log(`index-syntax.test.js: OK (${scripts.length} scripts)`);
