const assert = require("node:assert/strict");
const fs = require("node:fs");
const vm = require("node:vm");

const html = fs.readFileSync(require("node:path").resolve(__dirname, "..", "index.html"), "utf8");
const assistant = fs.readFileSync(require("node:path").resolve(__dirname, "..", "js", "app-assistant.js"), "utf8");
const scripts = [...html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi)].map((match) => match[1]).filter((source) => source.trim());
assert.ok(scripts.length > 0, "index.html deve possuir scripts inline");
scripts.forEach((source, index) => new vm.Script(source, { filename: `index-inline-${index + 1}.js` }));
const musicPane = html.slice(html.indexOf('id="pane-musicas"'), html.indexOf('id="pane-setlists"'));
assert.ok(musicPane.indexOf('class="youtube-panel"') < musicPane.indexOf('class="search-bar"'), "a busca do YouTube deve aparecer antes da busca da playlist");
assert.match(musicPane, /placeholder="Buscar música na playlist"/);
assert.match(musicPane, /Encontre um vídeo para adicionar à sua playlist/);
assert.match(musicPane, /ai-generate-action/, "a integração não deve remover o atalho de IA já aprovado no PR #48");
assert.match(musicPane, /aria-label="Limpar busca do YouTube"/);
assert.match(musicPane, /aria-label="Limpar busca da playlist"/);
assert.match(musicPane, /id="playlist-voice-search"/, "a busca da playlist deve oferecer o botão de voz");
assert.match(html, /#view-sd>#sd-content\{width:min\(100%,920px\);margin-inline:auto/, "o detalhe do evento deve ficar centralizado no desktop");
assert.match(html, /#view-detail:not\(\.stage-mode\)\[style\*="display: flex"\]/, "o layout em duas colunas deve ser exclusivo da tela da música");
assert.match(html, /window\.SpeechRecognition\|\|window\.webkitSpeechRecognition/, "a busca por voz deve usar a API compatível do navegador");
assert.match(html, /input\.value=spoken;\s*renderMusicas\(\)/, "o resultado falado deve preencher e filtrar a playlist");
assert.match(html, /function exactVoiceSongMatch\(spoken\)/, "a busca por voz deve identificar uma música com título exato");
assert.match(html, /if\(exactSong\)openDetail\(exactSong\.id\)/, "uma correspondência exata deve abrir a música diretamente");
assert.match(html, /id="app-assistant-floating"/, "o assistente deve permanecer disponível nas telas internas");
assert.match(html, /id="song-assistant-launch"/, "a tela da música deve manter o assistente no cabeçalho");
assert.match(html, /id="event-assistant-launch"/, "a tela do evento deve manter o assistente no cabeçalho");
assert.match(assistant,/data-account-menu-open/,'oculto nos menus da conta');
console.log(`index-syntax.test.js: OK (${scripts.length} scripts)`);
