const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
let clock=0;const context={window:{},Math,Number,Object,Array,String,performance:{now:()=>clock},setTimeout,clearTimeout};
vm.createContext(context);vm.runInContext(fs.readFileSync('js/smart-scroll.js','utf8'),context);
const smart=context.window.smartScroll;
assert.equal(smart.chordRoot('Cmaj7'),0);assert.equal(smart.chordRoot('C#m7'),1);assert.equal(smart.chordRoot('Db/F'),1);assert.equal(smart.chordRoot('Bb'),10);assert.equal(smart.chordRoot('(2x)'),null);assert.equal(smart.noteFromFrequency(440),9);
const blocks=[{dataset:{smartChords:'A D A G D A B7 E'}},{dataset:{smartChords:'E A B'}}];
const sequence=smart.buildSequence(blocks);assert.equal(sequence.length,11);assert.deepEqual(Array.from(sequence.slice(0,8),item=>item.chord),['A','D','A','G','D','A','B7','E']);assert.equal(sequence[8].blockIndex,1);
const tracker=smart.createTracker({stableMs:250,cooldownMs:180});tracker.reset(sequence);
const repeated=smart.buildSequence([{dataset:{smartChords:'G Em C G D',smartRepeat:'4'}},{dataset:{smartChords:'C D Em (2x)'}},{dataset:{smartChords:'C D Em D'}}]);
assert.equal(repeated.length,30);assert.equal(repeated[5].repetition,2);assert.equal(repeated[19].repetition,4);assert.equal(repeated[20].blockIndex,1);assert.equal(repeated[26].blockIndex,2);
const repeatTracker=smart.createTracker({stableMs:250,cooldownMs:180});repeatTracker.reset(repeated);
let repeatTime=10000,lastResult;
for(let i=0;i<20;i++){repeatTracker.sample(null,repeatTime);repeatTime+=300;repeatTracker.sample(repeatTracker.current().root,repeatTime);repeatTime+=250;lastResult=repeatTracker.sample(repeatTracker.current().root,repeatTime);assert.equal(lastResult.advanced,true);repeatTime+=300;if(i<19)assert.equal(repeatTracker.current().blockIndex,0,'não sai da linha antes das quatro voltas');}
assert.equal(repeatTracker.current().blockIndex,1,'avança somente depois da quarta volta');
repeatTracker.sample(null,repeatTime+10000);assert.equal(repeatTracker.getIndex(),20,'silêncio preserva a contagem');
assert.equal(smart.repeatCount('Solo 2x'),2);assert.equal(smart.repeatCount('G D (3×)'),3);assert.equal(smart.repeatCount('G D (0x)'),1);
assert.equal(tracker.sample(9,0).advanced,false);assert.equal(tracker.sample(9,249).advanced,false);let result=tracker.sample(9,250);assert.equal(result.advanced,true);assert.equal(result.current.chord,'D');assert.equal(tracker.sample(2,400).advanced,false);assert.equal(tracker.sample(2,650).advanced,true);tracker.sample(null,700);tracker.sample(9,800);assert.equal(tracker.sample(9,1050).advanced,true,'silêncio rearma acordes repetidos');tracker.align(1);assert.equal(tracker.current().blockIndex,1,'rolagem manual realinha no primeiro acorde do bloco');
const intermittent=smart.createTracker({stableMs:250,cooldownMs:180,dropoutMs:220});intermittent.reset(sequence);assert.equal(intermittent.sample(9,0).advanced,false);assert.equal(intermittent.sample(null,120).advanced,false);assert.equal(intermittent.sample(9,270).advanced,true,'uma pequena falha do microfone não deve cancelar uma nota correta');
tracker.reset(sequence);tracker.seek(5);assert.equal(tracker.getIndex(),5,'atualização visual preserva o progresso exato');tracker.sample(null,5000);assert.equal(tracker.getIndex(),5,'silêncio não reinicia o acompanhamento');
const html=fs.readFileSync('index.html','utf8');assert.match(html,/Rolagem inteligente/);assert.match(html,/smart-scroll-beta">BETA/);assert.match(html,/data-smart-line/);assert.match(html,/data-smart-chords=/);assert.match(html,/data-smart-chord-token=/);assert.match(html,/smart-chord-played/);assert.match(html,/function closeDetail\(\)\{\s*stopSmartScroll\(\)/);
assert.doesNotMatch(html,/currentSongView==='full'\)\{currentSongView='summary'/,'a rolagem inteligente deve permanecer em Letra + Cifras');
assert.match(html,/function renderSmartFullChordLine\(chordLine\)/,'Letra + Cifras precisa expor linhas para a rolagem inteligente');assert.match(html,/chordLine\?renderSmartFullChordLine\(chordLine\)/,'cifra completa estruturada precisa usar o rastreamento');assert.match(html,/isChordLine\(text\)\) return renderSmartFullChordLine\(shiftText\(text,totalShift\)\)/,'cifra completa em texto precisa usar o rastreamento');
assert.match(html,/🗑️ Excluir da Playlist<\/button>/);
assert.match(html,/state\.completed\)\{status\.textContent='Cifra concluída'/);assert.match(html,/remove\('smart-chord-played','smart-chord-current'\)/);
let frequencyHandler=null,stops=0;const scrollCalls=[];
const chordElement=chord=>({dataset:{smartChordToken:chord}});
const line=(chord,top)=>({dataset:{smartChords:chord},querySelectorAll:()=>[chordElement(chord)],getBoundingClientRect:()=>({top:top-container.scrollTop})});
const renderedLines=[line('A',120),line('D',480)];
const listeners={};const container={scrollTop:0,clientHeight:600,querySelectorAll:selector=>selector==='[data-smart-line]'?renderedLines:[],getBoundingClientRect:()=>({top:0}),addEventListener(type,listener){listeners[type]=listener;},removeEventListener(){},scrollTo(options){scrollCalls.push(options);this.scrollTop=options.top;}};
const updates=[];const controller=smart.create({stableMs:250,cooldownMs:180,tuner:{start(callback){frequencyHandler=callback;return Promise.resolve(true);},stop(){stops++;}}});
controller.start(container,state=>updates.push(state)).then(()=>{clock=0;frequencyHandler(440);clock=250;frequencyHandler(440);assert.equal(scrollCalls[0].behavior,'smooth');assert.ok(scrollCalls[0].top>=56,'fim da linha avança suavemente a tela');const savedIndex=controller.tracker.getIndex();clock=2000;listeners.wheel();listeners.scroll();assert.equal(controller.tracker.getIndex(),savedIndex,'arrastar a tela não altera o acorde acompanhado');container.scrollTop=700;clock=2100;frequencyHandler(293.6648);assert.ok(scrollCalls.at(-1).top<700,'a nota esperada realinha a tela à linha acompanhada');clock=2350;frequencyHandler(293.6648);assert.equal(scrollCalls.at(-1).top,0,'fim da música retorna ao topo');assert.equal(controller.isActive(),false,'fim da música pausa o acompanhamento');assert.ok(stops>0);assert.equal(updates.at(-1).completed,true);console.log('smart-scroll.test.js: OK (linhas, gesto manual neutro, realinhamento por nota e conclusão)');}).catch(error=>{console.error(error);process.exitCode=1;});
