const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const { chromium } = require('playwright');
const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
assert.doesNotMatch(html, /openStageConfiguration|renderStageConfiguration|stageConfigDraft|Configurar Modo Palco|reconfigureStageMode/);
const server = http.createServer((req, res) => {
  const pathname = new URL(req.url, 'http://localhost').pathname;
  const file = path.resolve(root, pathname === '/' ? 'index.html' : pathname.slice(1));
  if (!file.startsWith(root + path.sep) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) return res.writeHead(404).end();
  res.setHeader('Content-Type', ({'.html':'text/html; charset=utf-8','.js':'application/javascript','.css':'text/css','.png':'image/png','.webmanifest':'application/manifest+json'})[path.extname(file)] || 'application/octet-stream');
  fs.createReadStream(file).pipe(res);
});
(async () => {
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const executablePath = [process.env.BROWSER_EXECUTABLE, 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'].find(p => p && fs.existsSync(p));
  const browser = await chromium.launch({headless:true, executablePath});
  try {
    for (const viewport of [{width:390,height:844},{width:768,height:1024},{width:1366,height:768}]) {
      const context = await browser.newContext({viewport});
      const page = await context.newPage();
      const errors = [];
      page.on('pageerror', e => errors.push(e.message));
      await page.route('**/api/**', route => route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({enabled:false,provider:'local'})}));
      await page.route('https://fonts.googleapis.com/**', route => route.fulfill({status:200,contentType:'text/css',body:''}));
      await page.goto(`http://127.0.0.1:${server.address().port}/`);
      await page.evaluate(() => {
        const song = songModel.create({id:'stage-test',title:'Teste de palco',key:'C',youtubeVideoId:'video-123',blocos:[{l:'Refrão',c:'C G Am F\nFrase do resumo'}],fullChordSheet:{visibility:'private',source:'user_text',content:'INTRO\nC G Am F\nLetra completa do teste'}});
        musicas.push(song);
        stagePreferences.save(appCurrentUser.id,{contentMode:'lyrics',autoScroll:true,fullscreen:true,showNext:false});
        openDetail(song.id);
        setSongView('full');
      });
      assert.equal(await page.locator('#capo-row').isVisible(),true);
      assert.equal(await page.locator('#detail-capo-value').innerText(),'Sem');
      const originalSong=await page.evaluate(() => JSON.stringify(musicas.find(song=>song.id==='stage-test')));
      await page.locator('#capo-opt-2').click();
      assert.equal(await page.locator('#detail-capo-value').innerText(),'2');
      await page.evaluate(() => transpose(2));
      assert.equal(await page.locator('#transposed-key').innerText(),'D');
      const beforeStage=await page.locator('.full-chord-sheet').innerText();
      assert.match(beforeStage,/C G Am F/);
      await page.evaluate(() => enterStageMode());
      assert.equal(await page.locator('#stage-capo-value').isVisible(),true);
      assert.equal(await page.locator('#stage-capo-value').innerText(),'2');
      assert.equal(await page.locator('#stage-key').innerText(),'D');
      assert.equal(await page.getByRole('button',{name:'Sem capotraste',exact:true}).count(),0);
      assert.equal(await page.locator('#stage-scroll-toggle').innerText(),'Iniciar modo palco');
      const keyBounds=await page.locator('#stage-key').boundingBox();
      const controlBounds=await page.locator('.stage-capo-controls').boundingBox();
      assert.ok(keyBounds.y>=controlBounds.y&&keyBounds.y+keyBounds.height<=controlBounds.y+controlBounds.height);
      const titleBounds=await page.locator('.stage-heading').boundingBox();
      assert.ok(Math.abs(titleBounds.x+titleBounds.width/2-viewport.width/2)<2);
      const startBounds=await page.locator('#stage-scroll-toggle').boundingBox();
      const speedBounds=await page.locator('.stage-scroll-speed').boundingBox();
      assert.ok(startBounds.y>=speedBounds.y+speedBounds.height&&Math.abs(startBounds.x+startBounds.width/2-viewport.width/2)<2);
      assert.ok(startBounds.width<=200);
      assert.equal(await page.locator('#stage-online-status').count(),0);
      await page.evaluate(() => { document.getElementById('detail-content').style.minHeight='2500px'; });
      const expandedHeight=await page.locator('#stage-performance-header').evaluate(element=>element.getBoundingClientRect().height);
      await page.locator('#stage-scroll-toggle').click();
      assert.equal(await page.locator('#stage-scroll-toggle').innerText(),'Pausar Modo Palco');
      assert.equal(await page.locator('#view-detail.stage-scroll-compact').count(),1);
      assert.equal(await page.locator('.stage-capo-controls').isVisible(),false);
      assert.ok(await page.locator('#stage-performance-header').evaluate(element=>element.getBoundingClientRect().height)<expandedHeight);
      await page.locator('#stage-scroll-toggle').click();
      assert.equal(await page.locator('#stage-scroll-toggle').innerText(),'Iniciar modo palco');
      assert.equal(await page.locator('.stage-capo-controls').isVisible(),true);
      await page.locator('#stage-scroll-toggle').click();
      await page.evaluate(() => { const view=document.getElementById('view-detail');view.scrollTop=view.scrollHeight; });
      await page.waitForFunction(() => scrollTimer===null);
      assert.equal(await page.locator('#view-detail.stage-scroll-compact').count(),1);
      assert.equal(await page.locator('#stage-scroll-toggle').innerText(),'Pausar Modo Palco');
      await page.locator('#stage-scroll-toggle').click();
      assert.equal(await page.locator('.stage-capo-controls').isVisible(),true);
      await page.evaluate(() => { document.getElementById('detail-content').style.minHeight=''; });
      assert.equal(await page.locator('.full-chord-sheet').innerText(),beforeStage);
      await page.locator('#stage-capo-plus').click();
      assert.equal(await page.locator('#stage-capo-value').innerText(),'3');
      assert.equal(await page.locator('#transposed-key').innerText(),'D');
      assert.match(await page.locator('.full-chord-sheet').innerText(),/B Gb Abm E/);
      await page.locator('#stage-capo-minus').click();
      assert.equal(await page.locator('.full-chord-sheet').innerText(),beforeStage);
      await page.evaluate(() => selectCapo(0));
      assert.equal(await page.locator('#stage-capo-value').innerText(),'Sem');
      assert.match(await page.locator('.full-chord-sheet').innerText(),/D A Bm G/);
      await page.getByRole('button',{name:'Subir o tom',exact:true}).click();
      assert.equal(await page.locator('#stage-key').innerText(),'Eb');
      await page.getByRole('button',{name:'Descer o tom',exact:true}).click();
      assert.equal(await page.locator('#stage-key').innerText(),'D');
      assert.equal(await page.evaluate(() => JSON.stringify(musicas.find(song=>song.id==='stage-test'))),originalSong);
      const capoBounds=await page.locator('.stage-capo-controls').boundingBox();
      assert.ok(capoBounds.x>=0&&capoBounds.x+capoBounds.width<=viewport.width);
      assert.equal(await page.locator('#view-detail.stage-mode').count(),1);
      assert.equal(await page.locator('#modal-overlay').isVisible(),false);
      assert.match(await page.locator('#detail-content').innerText(),/Letra completa do teste/);
      assert.deepEqual(await page.evaluate(() => [scrollTimer,activeStagePreferences.contentMode,document.fullscreenElement]),[null,'lyrics-chords',null]);
      await page.getByRole('button',{name:'Sair do Modo Palco',exact:true}).click();
      assert.equal(await page.locator('#youtube-song-player.is-linked').isVisible(),true);
      await page.evaluate(() => {
        musicas.push(songModel.create({id:'capo-stored',title:'Capo gravado',key:'D',capo:'Capotraste casa 2',blocos:[{l:'',c:'C G/B Am F'}]}));
        openDetail('capo-stored');
      });
      assert.equal(await page.locator('#detail-capo-value').innerText(),'2');
      assert.match(await page.locator('#detail-content').innerText(),/C\s+G\/B\s+Am\s+F/);
      await page.locator('#capo-opt-0').click();
      assert.match(await page.locator('#detail-content').innerText(),/D\s+A\/Db\s+Bm\s+G/);
      assert.equal(await page.locator('#transposed-key').innerText(),'D');
      await page.locator('#capo-opt-2').click();
      assert.match(await page.locator('#detail-content').innerText(),/C\s+G\/B\s+Am\s+F/);
      await page.evaluate(() => {
        setlists.push(eventModel.create({id:'stage-event',title:'Repertório',musicas:['stage-test',1],members:[{...appCurrentUser,isLeader:true}],leaderId:appCurrentUser.id}));
        closeDetail();openSD('stage-event');
      });
      const sectionTitles=page.locator('#sd-content .event-section-title');
      assert.deepEqual(await sectionTitles.allTextContents(),['REPERTÓRIO OFICIAL DO EVENTO','Membros participantes']);
      assert.deepEqual(await sectionTitles.evaluateAll(elements=>elements.map(element=>getComputedStyle(element).textAlign)),['center','center']);
      const lastSongBounds=await page.locator('#sd-content .sd-row').last().boundingBox();
      const stageEntryBounds=await page.locator('.event-stage-entry').boundingBox();
      const eventContentBounds=await page.locator('#sd-content').boundingBox();
      const membersBounds=await sectionTitles.last().boundingBox();
      assert.ok(stageEntryBounds.y>=lastSongBounds.y+lastSongBounds.height&&membersBounds.y>=stageEntryBounds.y+stageEntryBounds.height);
      assert.ok(Math.abs(stageEntryBounds.x+stageEntryBounds.width/2-eventContentBounds.x-eventContentBounds.width/2)<2&&stageEntryBounds.height>=42);
      await page.locator('.event-stage-entry').click();
      assert.equal(await page.locator('#view-detail.stage-mode').count(),1);
      assert.equal(await page.locator('#stage-prev-preview').isVisible(),false);
      assert.equal(await page.locator('#stage-upcoming-preview').isVisible(),true);
      assert.equal(await page.locator('#stage-next-preview').count(),0);
      const headingInEvent=await page.locator('.stage-heading').boundingBox();
      const upcomingBounds=await page.locator('#stage-upcoming-preview').boundingBox();
      assert.ok(upcomingBounds.x>=headingInEvent.x+headingInEvent.width);
      await page.locator('#stage-scroll-toggle').click();
      assert.equal(await page.locator('#view-detail.stage-scroll-compact').count(),1);
      assert.equal(await page.locator('#stage-prev').isVisible(),true);
      assert.equal(await page.locator('#stage-next').isVisible(),true);
      assert.equal(await page.locator('#stage-upcoming-preview').isVisible(),true);
      const compactStart=await page.locator('#stage-scroll-toggle').boundingBox();
      const compactUpcoming=await page.locator('#stage-upcoming-preview').boundingBox();
      assert.ok(compactUpcoming.x>=compactStart.x+compactStart.width);
      await page.locator('#stage-next').click();
      assert.equal(await page.evaluate(() => String(currentDetailId)),'1');
      assert.equal(await page.locator('#view-detail.stage-scroll-compact').count(),1);
      assert.equal(await page.locator('#stage-prev-preview').isVisible(),true);
      await page.locator('#stage-scroll-toggle').click();
      assert.equal(await page.locator('#stage-prev-preview').isVisible(),true);
      assert.equal(await page.locator('#stage-prev-title').innerText(),'Teste de palco');
      const previousBounds=await page.locator('#stage-prev-preview').boundingBox();
      assert.ok(previousBounds.x+previousBounds.width<=headingInEvent.x);
      await page.locator('#stage-prev').click();
      assert.equal(await page.evaluate(() => currentDetailId),'stage-test');
      assert.equal(await page.locator('#view-detail.stage-mode').count(),1);
      assert.deepEqual(errors,[]);
      await context.close();
    }
    console.log('stage-direct-entry.test.js: OK (entrada direta, cifra completa, repertório, saída/YouTube e 3 viewports)');
  } finally { await browser.close(); server.close(); }
})().catch(e => { console.error(e); process.exitCode=1; });
