const assert=require('node:assert/strict');
global.window={};
require('../js/tablature.js');
require('../js/song-model.js');
const tab=window.tablature.normalize({instrument:'guitar',tuning:'E A D G B E',capo:2,sections:[{title:'Intro',content:'e|---0---|\r\nB|---1---|'}]});
assert.deepEqual(tab,{instrument:'guitar',tuning:'E A D G B E',capo:2,sections:[{title:'Intro',content:'e|---0---|\nB|---1---|'}]});
const parsed=window.tablature.parseEditor('[Intro]\ne|---0---|\n\n[Solo]\ne|--5/7--|');
assert.deepEqual(parsed.map(section=>section.title),['Intro','Solo']);
assert.equal(window.tablature.serializeEditor({...tab,sections:parsed}),'[Intro]\ne|---0---|\n\n[Solo]\ne|--5/7--|');
const song=window.songModel.create({title:'Teste',tablature:tab},{now:'2026-09-23T00:00:00.000Z'});
assert.equal(song.tablature.sections[0].content,'e|---0---|\nB|---1---|');
assert.equal(window.tablature.normalize({sections:[]}),null,'tablatura vazia não cria aba');
const html=require('node:fs').readFileSync('index.html','utf8');
assert.match(html,/setSongView\('tablature'\)/);assert.match(html,/id="simple-editor-tablature"/);assert.match(html,/tablature-scroll/);
console.log('tablature.test.js: OK (normalização, seções, persistência e interface)');
const guitar='[Solo]\nD|---0---|\nA|---0---|\nF|---0---|\nC|---0---|\nG|---0---|\nC|---0---|';
const uke='[Riff 1]\nA|---0---|\nE|---0---|\nC|---0---|\nG|---0---|';
const bass='[Riff 2]\nG|---0---|\nD|---0---|\nA|---0---|\nE|---0---|';
const extracted=window.tablature.extract('C G\nLetra mantida\n'+guitar+'\n\n'+uke+'\n\n'+bass);
assert.deepEqual(extracted.sections.map(s=>s.title),['Solo','Riff 1','Riff 2']);
assert.deepEqual(extracted.sections.map(s=>s.instrument),['guitar','ukulele','bass']);
assert.equal(extracted.content.includes('D|'),false);assert.match(extracted.content,/Letra mantida/);
const separated=window.tablature.prepareSong({title:'Tab mista',fullChordSheet:{content:guitar+'\n\n'+uke+'\n\n'+bass}});
for(const instrument of ['guitar','ukulele','bass'])assert.equal(window.tablature.compatible(separated.tablature,instrument).sections.length,1);
assert.equal(window.tablature.compatible(separated.tablature,'keyboard'),null);
assert.equal(window.tablature.prepareSong(separated).tablature.sections.length,3,'reextração não duplica');
assert.equal(window.tablature.identify(['Eb','Bb','Gb','Db','Ab','Eb']).instrument,'guitar');
assert.equal(window.tablature.identify(['F','C','G','C']).instrument,'bass','Drop C de baixo não vira ukulele pela nota C');
assert.equal(window.tablature.identify(['E','B','G','D']).instrument,'unknown','fragmento ambíguo exige indicação explícita');
assert.equal(window.tablature.extract('Instrumento: ukulele\nAfinação: D G B E\nE|---0---|\nB|---0---|\nG|---0---|\nD|---0---|').sections[0].instrument,'ukulele');
const migrated=window.songModel.create({title:'Importação',fullChordSheet:{content:'C G\nLetra\n'+guitar}});
assert.equal(migrated.tablature.sections[0].title,'Solo');assert.equal(migrated.fullChordSheet.content.includes('D|'),false);
