window.DEFAULT_MUSICAS = [
  {id:1,title:'A alegria',key:'A',capo:'',blocos:[{l:'A alegria',c:'A  D  A  G D\nA  B7  E'},{l:'O sentimento',c:'A  A7  D  F\nA  E  A  E'},{l:'posso pisar numa tropa',c:'A  A7  D  F  (3x)\nA  E  A  E'},{l:'Aleluia',c:'A  D  A\nB7  E'}]},
  {id:2,title:'A Ele a glória',key:'G',capo:'',blocos:[{l:'',c:'C  D  Em\nC  D  G  D  Em'}]},
  {id:3,title:'A casa é sua',key:'G',capo:'',blocos:[{l:'Você é bem vindo aqui',c:'G  Em7  C  G  C/G  G'},{l:'Essa casa é sua',c:'C  D4  Em  Bm7'},{l:'Apareça',c:'C  Am7  G  Bm7'}]},
  {id:4,title:'Além do impossível',key:'A',capo:'Capotraste casa 2',blocos:[{l:'Eu creio no Deus',c:'Em  D  G'},{l:'Em ti',c:'C  D  Em  G'}]},
  {id:5,title:'Alfa e Ômega',key:'E',capo:'Capotraste casa 2',blocos:[{l:'Não há outro como tu',c:'G  D  G  D'},{l:'Não há outro',c:'G  Bm7  G  A'},{l:'És o Alfa e Ômega',c:'D  A9  G  Em7  A\nBm7  A  D  G  Em7  A'},{l:'Alfa e Ômega',c:'D  Em  G'}]},
  {id:6,title:'Algo novo',key:'C',capo:'',blocos:[{l:'',c:'C  G'},{l:'',c:'Am7  F  C  G'},{l:'',c:'Am7  G  F'}]},
  {id:7,title:'Altar',key:'C',capo:'',blocos:[{l:'Deus me chamou',c:'C  G  F'},{l:'Estou aqui',c:'C  G  Am  G  F'}]},
  {id:8,title:'Alvo mais que a neve',key:'A',capo:'',blocos:[{l:'',c:'A  E  D  A\nA  D  A  E  A'}]},
  {id:9,title:'Amar como Você',key:'G',capo:'Capotraste casa 2',blocos:[{l:'',c:'G  C  G  C'},{l:'',c:'C  D  Em  G'}]},
  {id:10,title:'Ao Único',key:'C',capo:'',blocos:[{l:'Ao único',c:'C  G/B  Am  F  C  Dm  G'},{l:'Ao Rei',c:'C  F  Fm  C  G  C\nG/B'},{l:'Coroamos a ti',c:'Am  Em  F  C  G/B\nAm  Em  F  C'},{l:'Adoramos o teu nome',c:'F  G  E  Am  Dm  G  C'}]},
  {id:11,title:'Atos 2',key:'E',capo:'Capotraste casa 4',blocos:[{l:'',c:'Am  F  C  Em  (5x)\n                   G'},{l:'',c:'F  G  Am  G/B  C  F  G  (2x)'},{l:'',c:'F  Am  C  G'}]},
  {id:12,title:'Até que o Senhor venha',key:'C#m',capo:'Capotraste casa 4',blocos:[{l:'Oh se vc rasgar o céu',c:'Am  C  (4x)'},{l:'Como nos tempos passados',c:'F  G  Am  C  (4x)\nF  G'},{l:'Fere em meu coração',c:'Am  G  F  Dm'},{l:'Avivanos Senhor',c:'F  G  Am  G\nF  G  Am  C'}]},
  {id:13,title:'Aviva-nos / A terra clama',key:'Am',capo:'',blocos:[{l:'Enche esse ambiente',c:'F  G  Am  Em'}]},
  {id:14,title:'Boa parte',key:'E',capo:'',blocos:[{l:'Precioso Jesus',c:'E  A  E'},{l:'Tudo o que tenho',c:'E  A  E  C#m  A  E'},{l:'Eu entrei o meu tesouro',c:'E  A  E'},{l:'Como Maria',c:'B  A  B  A'}]},
  {id:15,title:'Bom perfume',key:'F',capo:'Capotraste casa 3',blocos:[{l:'',c:'D  A  G  (2x)'},{l:'',c:'Bm7  A  G  (4x)\n              Em'},{l:'',c:'D  G  Bm  A  G  Em'},{l:'',c:'D  A  Em  G\nBm  A  G  Em'}]},
  {id:16,title:'Canção de Simeão',key:'A',capo:'Capotraste casa 2',blocos:[{l:'Os meus olhos viram',c:'C  G  C  G'},{l:'E eu não sou mais meu',c:'Em  G  C  Em  G  C'},{l:'És Fome que me faz',c:'Am  G  C  (3x)'},{l:'E o olhar que vejo',c:'Am  G  D4  D'},{l:'E essa é minha promessa',c:'C  G  C  G'},{l:'Esse é o meu anseio',c:'Am  G  C  G'}]},
  {id:17,title:'Cordeiro e Leão',key:'G',capo:'',blocos:[{l:'De quem é esse amor',c:'C  Em7'},{l:'Seu nome é Jesus',c:'C  D  Em'}]},
  {id:18,title:'Cultura do céu',key:'C',capo:'',blocos:[{l:'Aqui na terra',c:'F  Am  G'},{l:'Venha o teu reino',c:'F  G  F  G'},{l:'Te convidamos',c:'F  Am  Em  G'},{l:'E toma o teu lugar',c:'F  Am  G'}]},
  {id:19,title:'Deserto',key:'C',capo:'',blocos:[{l:'',c:'Am  C  F9  (2x)'},{l:'Eu não preciso transformar',c:'C  G/B  Am  G  F9  C  Dm  G  C'},{l:'Não troco nossa comunhão',c:'C  G/B  Am  Bb2  Dm  C  F9'},{l:'E Te adorar',c:'Am  F9  C  G\nDm  F9  C  G'},{l:'Posso não ver',c:'Am  F9  C  G\nDm  F9'}]},
  {id:20,title:'Desenvolvendo amor',key:'G',capo:'',blocos:[{l:'Tua palavra é uma semente',c:'G  D  Am'},{l:'Então Deus',c:'Em  Bm7  Am  D  D#'},{l:'Vou crescendo',c:'Em  Bm7  Am  D'},{l:'Sim, Eu serei',c:'Bm7  Am  Bm7  Am  Bm7  D'}]},
  {id:21,title:'Digno de Tudo',key:'D',capo:'',blocos:[{l:'',c:'G  A  (3x)\nD  G  A  D'},{l:'',c:'D  A  G  A  D'},{l:'',c:'D  F#m  Bm  G\nD  A  Em  G'},{l:'',c:'D  F#m  G  A  D'}]},
  {id:22,title:'Digno de Tudo + Te Exalt',key:'C',capo:'',blocos:[{l:'Os Santos e os anjos',c:'F  G  F  G'},{l:'Os anciãos',c:'F  G  C  F  G  C'},{l:'Tu és digno de tudo',c:'C  G  F  G  C'},{l:'Dia e noite',c:'C  G  Dm7  F\nC  Em  Am  F'},{l:'Te Exaltamos',c:'C  Em7  F  G  C'}]},
  {id:23,title:'Digno é o Senhor',key:'D',capo:'',blocos:[{l:'',c:'Bm7  A  G  (2x)'},{l:'',c:'G  D  G  A  D'},{l:'',c:'Bm7  A  G  Em  Bm7  A'},{l:'',c:'D  A  Em  D  G\nA  G  D  G  A\nEm  Bm7  A'}]},
  {id:24,title:'É Ele',key:'A',capo:'',blocos:[{l:'Estou preparando um caminho',c:'A  F#m  D  A  (2x)'},{l:'Nele meu prazer estar',c:'D  F#m  A  E  (2x)'},{l:'E é ele',c:'D  E  F#m  C#m  D  E  (2x)'},{l:'E Ele virá',c:'A  F#m  D  E  (2x)'}]},
  {id:25,title:'Ekballo',key:'Am',capo:'',blocos:[{l:'Formoso Ele é',c:'Am  G  F'},{l:'Maranata, ora vem',c:'F  G  Am  C'}]},
  {id:26,title:'Em seu nome',key:'G',capo:'',blocos:[{l:'Só um nome há',c:'G  Bm  C  (2x)'},{l:'O nome de Jesus',c:'Am7  G/B  C  D  (2x)'},{l:'Em seu nome',c:'C  D'}]},
  {id:27,title:'Em teus braços',key:'C',capo:'',blocos:[{l:'',c:'F  C  F  C'},{l:'',c:'Am  F  G  Em  F  G'},{l:'',c:'F  C  F  C'}]},
  {id:28,title:'Emaus',key:'A',capo:'',blocos:[{l:'Introdução',c:'D  F#m7  E  A\nD  F#m7  E'},{l:'Quem é esse que vem',c:'D  A  D  A  E'},{l:'Ele é tão sábio',c:'D  E  D  E'},{l:'Ele entrou em casa',c:'D  E  F#m7  E'},{l:'E ao partir o pão',c:'Bm7  A9  D  E  (2x)'},{l:'Nós arrumamos a casa',c:'D  F#m7  E  A'}]},
  {id:29,title:'Encontrei o meu lugar',key:'E',capo:'',blocos:[{l:'Só em ti Jesus',c:'C#m  A  E  B  (2x)'},{l:'Tomou minhas dores',c:'A  B  C#m  E'}]},
  {id:30,title:'Encontre aqui',key:'G#m',capo:'Capotraste casa 4',blocos:[{l:'',c:'Em  C'},{l:'',c:'C  D  Em  D  (2x)'},{l:'',c:'C  D  Bm  Em'},{l:'',c:'Am  Bm  C  D'}]},
  {id:31,title:'Escape',key:'C',capo:'',blocos:[{l:'Introdução',c:'C  C4  C  C4'},{l:'O inimigo',c:'C  C4  C  G  (2x)'},{l:'Aquele que acalma o vento',c:'C  C4  Am  G'},{l:'O Deus que derruba muralhas',c:'C  F  C  G'},{l:'Deus já tem',c:'F  Am  G'},{l:'Leão da tribo de Judá',c:'Am  A#  Dm  A#  F  A#  Dm  E7\nAm  F  C'},{l:'Reina para sempre',c:'G  Am  F  C\nG  F'}]},
  {id:32,title:'Escudo',key:'C',capo:'',blocos:[{l:'',c:'C  Dm  G  C'},{l:'',c:'Am7  Em  F  G  C'}]},
  {id:33,title:'Estamos de pé',key:'A',capo:'',blocos:[{l:'Pressionados',c:'A  F#m  D  A  (2x)'},{l:'Nação Santa',c:'A  E  Bm  A  D\nA  E  G  D  A'},{l:'A perseguição não parou',c:'A  Em  G  D  (2x)'}]},
  {id:34,title:'Eu e minha casa',key:'A',capo:'Capotraste casa 2',blocos:[{l:'Introdução',c:'C  D  Em7  Bm'},{l:'Bendita será nossa casa',c:'G2  Em7  C9  G2  (2x)'},{l:'A rocha em que minha casa',c:'C  D9  Em7  Bm7  (2x)'},{l:'Meu Jesus',c:'G2  D9  Em7  C  (2x)'},{l:'ooo ooo',c:'G2  Am7  G/B  C  (2x)'}]},
  {id:35,title:'Eu era órfão',key:'A',capo:'',blocos:[{l:'',c:'D9  E  F#m7'},{l:'',c:'A9  D9  F#m7  D9  A9'},{l:'',c:'D9  E  F#m7  C#m7'}]},
  {id:36,title:'Eu me rendo',key:'Em',capo:'',blocos:[{l:'',c:'Em  G  D  C'},{l:'',c:'Em  G  Am  C  (2x)'},{l:'',c:'C  G  D  Am  Em  D'}]},
  {id:37,title:'Eu navegarei',key:'Am',capo:'',blocos:[{l:'',c:'Am  G  Dm  F  E7'}]},
  {id:38,title:'Eu tenho você',key:'C',capo:'',blocos:[{l:'Vou falar',c:'C  F  Am7'},{l:'Eu estava longe',c:'Dm  C  F  G  (2x)'},{l:'Não me abandonou',c:'C  Am7  Dm  F'},{l:'Eu vaguei',c:'F  C  Dm  F'},{l:'Só faltava eu perceber',c:'G  C'}]},
  {id:39,title:'Eu vou construir',key:'C',capo:'',blocos:[{l:'Digno desta canção',c:'C  F  C  F'},{l:'Santo',c:'F  Dm  C  Am'},{l:'Eu vou construir',c:'F  G  Am7  Em7'}]},
  {id:40,title:'Filhos do teu amor',key:'D',capo:'',blocos:[{l:'Oooo ooo oooo',c:'Bm  A  G  F#'},{l:'Nos levantamos',c:'G  A  G  A'},{l:'Filhos do teu amor',c:'G  Bm  D  E'},{l:'Somos aqueles',c:'Bm  A  G  Em'}]},
  {id:41,title:'Foi de Graça',key:'G',capo:'',blocos:[{l:'Eu tentei',c:'C  Em  C  Em'},{l:'me aceitou desde sempre',c:'C  D  C  D'},{l:'Foi de graça',c:'C  G  D'}]},
  {id:42,title:'Furioso oceano',key:'Em',capo:'',blocos:[{l:'Pode entrar',c:'C  D  Em  Bm7'},{l:'Furioso oceano',c:'C  Am7  Em  Bm7'}]},
  {id:43,title:'Gratidão',key:'A',capo:'',blocos:[{l:'Nada novo achei / Em resposta a ti',c:'A  F#m  E  D  (2x)'},{l:'Então vou levantar / Ei meu coração',c:'A  E  D  F#m  E  (2x)'}]},
  {id:44,title:'Inexplicável amor',key:'C',capo:'',blocos:[{l:'O amor que surpreende',c:'C  F  (4x)'},{l:'Nada faz vc parar de me amar',c:'F  Am7  Em7\nF  Am7  G'},{l:'Que amor é esse',c:'C  C  F  G  F'},{l:'Amor que constrange',c:'F  G  Am  C'}]},
  {id:45,title:'Liberta-me de mim',key:'E',capo:'',blocos:[{l:'Não entendo',c:'A9  B4  E'},{l:'Pois o bem',c:'A9  B4  E  C#m7'},{l:'Mas eu sei',c:'A9  B4  E  F#m7(11)'}]},
  {id:46,title:'Lindo momento',key:'D',capo:'',blocos:[{l:'',c:'Em  G  D  A9'}]},
  {id:47,title:'Maranata',key:'Am',capo:'',blocos:[{l:'Tu és a minha luz',c:'Am  F  C  G  (2x)'},{l:'O o ooo',c:'F  G  Am  C  G  (2x)'},{l:'Só em ti confiarei',c:'F  C  Am  G  (2x)'},{l:'Vem Jesus',c:'C  F  C  G'}]},
  {id:48,title:'Me ama',key:'A',capo:'',blocos:[{l:'',c:'A  D  E  D'}]},
  {id:49,title:'Não negociamos princípios',key:'Am',capo:'',blocos:[{l:'Ainda existem os que',c:'Am  G  F  Dm'},{l:'Ainda existem aqueles',c:'Am  G  F'}]},
  {id:50,title:'O espírito de Deus está aqui',key:'C#m',capo:'',blocos:[{l:'',c:'C#m  B  E  (2x)\nC#m  B  E  B'},{l:'',c:'C#m  B  F#m  B'}]},
  {id:51,title:'O grito',key:'C',capo:'',blocos:[{l:'',c:'C  F  C  F'},{l:'',c:'Am  F  C  G'}]},
  {id:52,title:'O que sua glória fez comigo',key:'Dm',capo:'',blocos:[{l:'Introdução',c:'Bb  C  Am  Dm'},{l:'Eu me rasgo',c:'Bb  Gm7  Am  Dm'},{l:'E se eu passar',c:'Bb  Gm7  C  Am'},{l:'Longe do Santo dos Santos',c:'Bb  Gm7  C'},{l:'Quem já pisou / E onde estiver',c:'Bb  C  Am  Dm\nBb  C  F4  F4  F'},{l:'Glória / Santo',c:'Bb  C  Am  Dm'}]},
  {id:53,title:'Pode morar aqui',key:'C',capo:'',blocos:[{l:'Minhas lamparinas',c:'C  Am  C  Am'},{l:'É só bater que eu',c:'Em  F  C  G  (2x)'},{l:'Eu já coloquei',c:'F  C  Am  G  F  G  F  G'},{l:'Tem fogo nos olhos',c:'F  G  Am  Em'}]},
  {id:54,title:'Poderoso Deus',key:'A',capo:'',blocos:[{l:'Ao que está assentado',c:'A9  F#m7  D9  Bm7  E'},{l:'Quem já pisou',c:'D9  E  C#m7  F#m7\nD9  E  A9'},{l:'Glória',c:'D9  E  C#m7  F#m7'}]},
  {id:55,title:'Porque Ele vive',key:'C',capo:'',blocos:[{l:'',c:'C  F  C  G\nC  F  C  G  F'},{l:'Porque Ele vive',c:'C  F  C  Am  G\nC  F  C  G  F'}]},
  {id:56,title:'Pra onde eu irei',key:'Am',capo:'',blocos:[{l:'Ele abriu mão',c:'C  Em7  Am  G  F  (2x)'},{l:'Pôs um anel',c:'Dm  Em  F  Em\nDm  Em  F  G'},{l:'E eu, me despedi',c:'F  Am  F  G  (2x)'},{l:'Pra onde eu irei',c:'F  G  Am  Em\nF  G'}]},
  {id:57,title:'Primeira essência',key:'C',capo:'Capotraste casa 4',blocos:[{l:'Estou no meu jardim',c:'C  G/B  Am  G  F  Em  Dm  G  (2x)'},{l:'Senhor, não quero',c:'F  G  C  G  F  Em  Dm'},{l:'Não quero que em mim',c:'Dm  G  F  G'},{l:'Vem Senhor',c:'C  G/B  Am  G  F  Em  Dm  G  (2x)'},{l:'Te adoro',c:'Am  G  F  C  (2x)\nC  C  G'}]},
  {id:58,title:'Que ele cresça',key:'D',capo:'',blocos:[{l:'',c:'D  G  D  G'},{l:'',c:'Bm  A  G'},{l:'',c:'Em  G  Bm  A'}]},
  {id:59,title:'Quebrantado',key:'D',capo:'Capotraste casa 2',blocos:[{l:'',c:'C  G  Am  F  (2x)'},{l:'',c:'C  Am  G  F  (2x)'},{l:'',c:'Dm  F  Dm  F  G  (2x)'}]},
  {id:60,title:'Quebra o silêncio',key:'D',capo:'',blocos:[{l:'Introdução',c:'Bm  A  G  (4x)'},{l:'Me atraiu',c:'Bm  A  G  Em  (3x)'},{l:'Então vem',c:'G  A  G  A'},{l:'Quebra o silêncio',c:'Bm  G  A  D  G'},{l:'Aqui',c:'Bm  A  G  Em'},{l:'Por trás dessa face',c:'Bm  A  G'}]},
  {id:61,title:'Quebro meu vaso',key:'G',capo:'Capotraste casa 4',blocos:[{l:'',c:'G  G/B  C9  D  (2x)'},{l:'',c:'Am7  G/B  Em7  D  (2x)'},{l:'',c:'G  G/B  C9  D'}]},
  {id:62,title:'Quando a luz se apagar',key:'Cm',capo:'Capotraste casa 3',blocos:[{l:'',c:'Am  G  Dm  Em'},{l:'',c:'C  Em  F  G'}]},
  {id:63,title:'Quando ele vem',key:'A',capo:'Capotraste casa 2',blocos:[{l:'',c:'C  G  D'}]},
  {id:64,title:'Quando o céu invade a terra',key:'F#m',capo:'',blocos:[{l:'Como no dia',c:'F#m7  D  A  C#m'},{l:'Quando eu escutar',c:'D  E  F#m7  A'}]},
  {id:65,title:'Quem é esse',key:'C#m',capo:'Capotraste casa 2',blocos:[{l:'',c:'A9  B2  G#m  C#m  (4x)'},{l:'',c:'F#11  G#m  A9'},{l:'',c:'E  C#m  A9  F#11  B2'},{l:'',c:'A9  B2  C#m  G#m'}]},
  {id:66,title:'Quem dera fosse hoje',key:'C',capo:'',blocos:[{l:'Você me chama de',c:'Am  C  G  D'}]},
  {id:67,title:'Quero conhecer Jesus',key:'G',capo:'',blocos:[{l:'Meu orgulho',c:'C  D  Em  Bm'},{l:'Yeshua',c:'C  D  Em  D'},{l:'Meu amado é',c:'C  Em  G  D'}]},
  {id:68,title:'Recebe a Cura',key:'G',capo:'',blocos:[{l:'Introdução',c:'D4  C9  D4  C9'},{l:'Se tentaram',c:'D4  C9  D4  Em'},{l:'Se lançaram',c:'Bm7  C9  Am  G'},{l:'Não desista',c:'C9  D  Em  G  D\nC9  D  Em  G'},{l:'Levanta teus olhos',c:'F  C  Am  D  Am  Em'},{l:'Recebe a Cura',c:'G  C9  Em  D  C9'}]},
  {id:69,title:'Ruja o Leão',key:'F#m',capo:'',blocos:[{l:'',c:'C#m  B  A  F#11\nC#m  A  C#m  B'}]},
  {id:70,title:'Santo pra sempre',key:'C',capo:'',blocos:[{l:'',c:'C  F  C  Am  G  F\n      Am  G  F'},{l:'',c:'F  G  Am  F\nF  G  Am  Dm'},{l:'',c:'F  G  Em  Am  Dm  G  C'}]},
  {id:71,title:'Saudade',key:'E',capo:'',blocos:[{l:'',c:'A9  E'}]},
  {id:72,title:'Se eu cair',key:'G',capo:'',blocos:[{l:'',c:'C7m  G  D'},{l:'',c:'C7m  Am7  G'},{l:'',c:'G  G/A  G/B  G/A  C7m  Am7  G  Bm7'}]},
  {id:73,title:'Só quero queimar',key:'C',capo:'',blocos:[{l:'',c:'C  G'}]},
  {id:74,title:'Sublime',key:'D',capo:'',blocos:[{l:'Quem é como Tu',c:'D  Bm  A  G\nD  Bm  A  G  A  D  Bm  A'},{l:'Maravilhoso, admirável',c:'G  A  D  Bm  A\nG  A  D  Bm  A  G'},{l:'Ah, como espero',c:'Em  D  A'}]},
  {id:75,title:'Te louvarei',key:'A',capo:'Capotraste casa 2',blocos:[{l:'Perto quero estar',c:'G  C  D  G'},{l:'Pois prazer maior não há',c:'D  C  Em  D  C'},{l:'Não sou apenas servo',c:'G  C  D  G'},{l:'Te louvarei',c:'G  D  C  G  D  C  D'},{l:'Adorarei',c:'G  D  C  Em  D  G'}]},
  {id:76,title:'Teu olhar é como fogo',key:'C',capo:'',blocos:[{l:'',c:'F  G  Em  Am\nF  G  Am'},{l:'',c:'F  G  Am  Em'}]},
  {id:77,title:'Teu Santo Nome',key:'F',capo:'Capotraste casa 3',blocos:[{l:'Todo ser que vive',c:'Em  Bm  G  D  (2x)'},{l:'E mesmo sendo pó',c:'Em  G  D  A  (2x)'},{l:'Todo joelho dobrará',c:'Bm  G  D  A  (2x)'}]},
  {id:78,title:'Teu toque',key:'A',capo:'',blocos:[{l:'',c:'D  F#m7  A  E  (3x)'},{l:'',c:'D  E  F#m7  A9'}]},
  {id:79,title:'Toda Terra',key:'G',capo:'',blocos:[{l:'Eu ouvi uma vez',c:'G  C  (2x)'},{l:'Toda Terra',c:'C  D  Em  Bm  C  (2x)'},{l:'Estamos juntando',c:'C  D  Bm  C'},{l:'Aleluia',c:'Am7  Bm  C  Em  D'}]},
  {id:80,title:'Tu és + É Ele',key:'A',capo:'Capotraste casa 2',blocos:[{l:'Tú És',c:'G  C  Am7  C  D'},{l:'Junto ao poço',c:'Em  D  C  (4x)'},{l:'Dá-me de beber',c:'Am7  G/B  C  G/B  (2x)'},{l:'E é Ele',c:'C  D  Em  Bm7  C  D'},{l:'E Ele virá',c:'Em  G  Am7  C'}]},
  {id:81,title:'Tu és Deus',key:'C',capo:'Capotraste casa 3',blocos:[{l:'',c:'A9  D9  F#11  E4'},{l:'',c:'D9  E4  A9  A4  A9'}]},
  {id:82,title:'Tudo é perda',key:'Db',capo:'Capotraste casa 1',blocos:[{l:'',c:'C  Am7  G  F'},{l:'',c:'F  G  C  F'},{l:'',c:'Dm  C  G  C  F'},{l:'',c:'Dm  G  C  F'}]},
  {id:83,title:'Tudo é teu',key:'A',capo:'Capotraste casa 2',blocos:[{l:'Cristo',c:'G  C  (2x)'},{l:'Ele partiu o pão',c:'Am7  G  C  (2x)'},{l:'Tudo que tenho é teu',c:'G  C  Em  D  C'}]},
  {id:84,title:'Único',key:'G',capo:'',blocos:[{l:'',c:'C  D  Em  G'}]},
  {id:85,title:'Uma nova história',key:'A',capo:'',blocos:[{l:'Sai de tua tenda',c:'F#m  E  B  D'},{l:'Filho meu',c:'F#m  E  D  B  D'},{l:'Uma nova História',c:'A  D  E'}]},
  {id:86,title:'Você me leva ao deserto',key:'A',capo:'',blocos:[{l:'Introdução',c:'F#m7  E  A9  (2x)'},{l:'Eu calei minha tristeza',c:'F#m7  E  A9  (2x)'},{l:'Eu coloquei os meus desejos',c:'D9  E  F#m7  D9  E'},{l:'Estou seguindo meu caminho',c:'F#m7  E  A9  (2x)'},{l:'Na tua identidade',c:'D9  E  F#m7  D9  E\nF#m7  E  A9'},{l:'Você me leva ao deserto',c:'F#m7  E  D9\nF#m7  E  A9  (2x)'},{l:'Pra me dizer no fim',c:'D  E  F#m7  E  A9'}]}
];
